// Generated by tools/GeneratePerkSync.py. Do not edit manually.
module SkillDrivenProgression

// Status of a shard grade in the save's vanilla perk purchases:
// 0 none bought, 1 partly bought, 2 fully bought, 3 grade has no vanilla perks.
@addMethod(PlayerDevelopmentData)
public final const func SDP_SyncGradeStatus(family: Int32, grade: Int32) -> Int32 {
  let total: Int32 = 0;
  let owned: Int32 = 0;
  if family == 0 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Left_Milestone_2) >= 2 { owned += 1; };
  };
  if family == 0 && grade == 2 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Left_Milestone_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Left_Perk_2_2) >= 1 { owned += 1; };
  };
  if family == 0 && grade == 3 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Inbetween_Left_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Left_Perk_2_4) >= 1 { owned += 1; };
  };
  if family == 0 && grade == 4 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Left_Perk_2_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Left_Perk_2_3) >= 1 { owned += 1; };
  };
  if family == 0 && grade == 5 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Left_Milestone_3) >= 3 { owned += 1; };
  };
  if family == 0 && grade == 6 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Left_Milestone_3) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Left_Perk_3_3) >= 1 { owned += 1; };
  };
  if family == 0 && grade == 7 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Left_Perk_3_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Left_Perk_3_4) >= 1 { owned += 1; };
  };
  if family == 0 && grade == 8 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Left_Perk_3_2) >= 1 { owned += 1; };
  };
  if family == 0 && grade == 9 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Left_Milestone_3) >= 2 { owned += 1; };
  };
  if family == 0 && grade == 10 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Master_Perk_2) >= 1 { owned += 1; };
  };
  if family == 0 && grade == 11 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Master_Perk_1) >= 1 { owned += 1; };
  };
  if family == 1 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Central_Milestone_1) >= 1 { owned += 1; };
  };
  if family == 1 && grade == 2 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Central_Milestone_3) >= 1 { owned += 1; };
  };
  if family == 1 && grade == 3 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Central_Perk_1_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Central_Perk_1_2) >= 1 { owned += 1; };
  };
  if family == 1 && grade == 4 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Central_Milestone_3) >= 2 { owned += 1; };
  };
  if family == 1 && grade == 5 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Central_Milestone_3) >= 3 { owned += 1; };
  };
  if family == 1 && grade == 6 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Central_Perk_1_4) >= 1 { owned += 1; };
  };
  if family == 1 && grade == 7 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Central_Perk_1_3) >= 1 { owned += 1; };
  };
  if family == 1 && grade == 8 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Central_Perk_3_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Inbetween_Left_3) >= 1 { owned += 1; };
  };
  if family == 1 && grade == 9 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Central_Perk_3_2) >= 1 { owned += 1; };
  };
  if family == 1 && grade == 10 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Central_Perk_3_4) >= 1 { owned += 1; };
  };
  if family == 1 && grade == 11 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Master_Perk_3) >= 1 { owned += 1; };
  };
  if family == 2 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Left_Milestone_2) >= 1 { owned += 1; };
  };
  if family == 2 && grade == 2 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Left_Milestone_2) >= 2 { owned += 1; };
  };
  if family == 2 && grade == 3 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Left_Perk_2_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Left_Perk_2_4) >= 1 { owned += 1; };
  };
  if family == 2 && grade == 4 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Left_Milestone_3) >= 1 { owned += 1; };
  };
  if family == 2 && grade == 5 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Left_Milestone_3) >= 3 { owned += 1; };
  };
  if family == 2 && grade == 6 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Left_Milestone_3) >= 2 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Left_Perk_2_3) >= 1 { owned += 1; };
  };
  if family == 2 && grade == 7 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Left_Perk_3_1) >= 1 { owned += 1; };
  };
  if family == 2 && grade == 8 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Left_Perk_3_2) >= 1 { owned += 1; };
  };
  if family == 2 && grade == 9 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Left_Perk_3_3) >= 1 { owned += 1; };
  };
  if family == 2 && grade == 10 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Left_Perk_3_4) >= 1 { owned += 1; };
  };
  if family == 2 && grade == 11 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Master_Perk_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Master_Perk_2) >= 1 { owned += 1; };
  };
  if family == 3 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Right_Milestone_2) >= 1 { owned += 1; };
  };
  if family == 3 && grade == 2 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Right_Milestone_2) >= 2 { owned += 1; };
  };
  if family == 3 && grade == 3 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Right_Perk_2_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Right_Perk_2_2) >= 1 { owned += 1; };
  };
  if family == 3 && grade == 4 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Right_Perk_2_3) >= 1 { owned += 1; };
  };
  if family == 3 && grade == 5 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Right_Milestone_3) >= 3 { owned += 1; };
  };
  if family == 3 && grade == 6 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Right_Milestone_3) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Right_Milestone_3) >= 2 { owned += 1; };
  };
  if family == 3 && grade == 7 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Right_Perk_2_4) >= 1 { owned += 1; };
  };
  if family == 3 && grade == 8 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Right_Perk_3_2) >= 1 { owned += 1; };
  };
  if family == 3 && grade == 9 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Right_Perk_3_1) >= 1 { owned += 1; };
  };
  if family == 3 && grade == 10 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Inbetween_Right_3) >= 1 { owned += 1; };
  };
  if family == 3 && grade == 11 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Master_Perk_5) >= 1 { owned += 1; };
  };
  if family == 4 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Milestone_1) >= 1 { owned += 1; };
  };
  if family == 4 && grade == 2 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Milestone_2) >= 2 { owned += 1; };
  };
  if family == 4 && grade == 3 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Milestone_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Perk_1_1) >= 1 { owned += 1; };
  };
  if family == 4 && grade == 4 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Perk_1_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Perk_1_3) >= 1 { owned += 1; };
  };
  if family == 4 && grade == 5 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Milestone_3) >= 3 { owned += 1; };
  };
  if family == 4 && grade == 6 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Milestone_3) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Milestone_3) >= 2 { owned += 1; };
  };
  if family == 4 && grade == 7 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Perk_2_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Perk_2_3) >= 1 { owned += 1; };
  };
  if family == 4 && grade == 8 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Perk_2_4) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Perk_1_4) >= 1 { owned += 1; };
  };
  if family == 4 && grade == 9 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Perk_3_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Perk_3_3) >= 1 { owned += 1; };
  };
  if family == 4 && grade == 10 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Central_Perk_2_1) >= 1 { owned += 1; };
  };
  if family == 4 && grade == 11 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Master_Perk_3) >= 1 { owned += 1; };
  };
  if family == 5 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Left_Milestone_2) >= 1 { owned += 1; };
  };
  if family == 5 && grade == 2 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Left_Milestone_2) >= 2 { owned += 1; };
  };
  if family == 5 && grade == 3 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Left_Perk_2_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Left_Perk_2_3) >= 1 { owned += 1; };
  };
  if family == 5 && grade == 4 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Left_Milestone_3) >= 1 { owned += 1; };
  };
  if family == 5 && grade == 5 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Left_Milestone_3) >= 3 { owned += 1; };
  };
  if family == 5 && grade == 6 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Left_Milestone_3) >= 2 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Left_Perk_3_3) >= 1 { owned += 1; };
  };
  if family == 5 && grade == 7 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Left_Perk_2_4) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Left_Perk_3_1) >= 1 { owned += 1; };
  };
  if family == 5 && grade == 8 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Left_Perk_3_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Inbetween_Left_3) >= 1 { owned += 1; };
  };
  if family == 5 && grade == 9 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Left_Perk_3_4) >= 1 { owned += 1; };
  };
  if family == 5 && grade == 10 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Master_Perk_2) >= 1 { owned += 1; };
  };
  if family == 5 && grade == 11 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Master_Perk_1) >= 1 { owned += 1; };
  };
  if family == 6 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Right_Milestone_2) >= 1 { owned += 1; };
  };
  if family == 6 && grade == 2 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Right_Milestone_2) >= 2 { owned += 1; };
  };
  if family == 6 && grade == 3 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Right_Perk_2_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Right_Perk_2_2) >= 1 { owned += 1; };
  };
  if family == 6 && grade == 4 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Right_Perk_2_3) >= 1 { owned += 1; };
  };
  if family == 6 && grade == 5 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Right_Milestone_3) >= 3 { owned += 1; };
  };
  if family == 6 && grade == 6 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Right_Milestone_3) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Right_Milestone_3) >= 2 { owned += 1; };
  };
  if family == 6 && grade == 7 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Inbetween_Right_2) >= 1 { owned += 1; };
  };
  if family == 6 && grade == 8 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Right_Perk_3_3) >= 1 { owned += 1; };
  };
  if family == 6 && grade == 9 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Right_Perk_3_4) >= 1 { owned += 1; };
  };
  if family == 6 && grade == 10 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Right_Perk_3_1) >= 1 { owned += 1; };
  };
  if family == 6 && grade == 11 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Master_Perk_5) >= 1 { owned += 1; };
  };
  if family == 7 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Central_Milestone_2) >= 1 { owned += 1; };
  };
  if family == 7 && grade == 2 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Central_Milestone_2) >= 2 { owned += 1; };
  };
  if family == 7 && grade == 3 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Central_Perk_2_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Central_Perk_2_3) >= 1 { owned += 1; };
  };
  if family == 7 && grade == 4 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Central_Milestone_3) >= 1 { owned += 1; };
  };
  if family == 7 && grade == 5 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Central_Milestone_3) >= 3 { owned += 1; };
  };
  if family == 7 && grade == 6 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Central_Milestone_3) >= 2 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Central_Perk_3_1) >= 1 { owned += 1; };
  };
  if family == 7 && grade == 8 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Central_Perk_3_3) >= 1 { owned += 1; };
  };
  if family == 7 && grade == 9 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Central_Perk_2_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Inbetween_Right_2) >= 1 { owned += 1; };
  };
  if family == 7 && grade == 10 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Central_Perk_2_4) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Central_Perk_3_4) >= 1 { owned += 1; };
  };
  if family == 7 && grade == 11 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Master_Perk_3) >= 1 { owned += 1; };
  };
  if family == 8 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Milestone_1) >= 1 { owned += 1; };
  };
  if family == 8 && grade == 2 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Milestone_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Perk_1_2) >= 1 { owned += 1; };
  };
  if family == 8 && grade == 3 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Milestone_2) >= 2 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Perk_1_1) >= 1 { owned += 1; };
  };
  if family == 8 && grade == 4 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Perk_2_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Perk_2_4) >= 1 { owned += 1; };
  };
  if family == 8 && grade == 5 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Milestone_3) >= 3 { owned += 1; };
  };
  if family == 8 && grade == 6 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Milestone_3) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Milestone_3) >= 2 { owned += 1; };
  };
  if family == 8 && grade == 7 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Perk_3_01) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Inbetween_Left_3) >= 1 { owned += 1; };
  };
  if family == 8 && grade == 8 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Perk_2_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Perk_2_3) >= 1 { owned += 1; };
  };
  if family == 8 && grade == 9 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Perk_3_4) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Perk_3_2) >= 1 { owned += 1; };
  };
  if family == 8 && grade == 10 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Left_Perk_3_3) >= 1 { owned += 1; };
  };
  if family == 8 && grade == 11 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Master_Perk_2) >= 1 { owned += 1; };
  };
  if family == 9 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Right_Milestone_3) >= 1 { owned += 1; };
  };
  if family == 9 && grade == 2 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Right_Milestone_3) >= 2 { owned += 1; };
  };
  if family == 9 && grade == 3 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Right_Perk_3_1) >= 1 { owned += 1; };
  };
  if family == 9 && grade == 5 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Right_Milestone_3) >= 3 { owned += 1; };
  };
  if family == 9 && grade == 6 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Right_Perk_3_2) >= 1 { owned += 1; };
  };
  if family == 9 && grade == 7 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Right_Perk_3_3) >= 1 { owned += 1; };
  };
  if family == 9 && grade == 8 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Right_Perk_3_4) >= 1 { owned += 1; };
  };
  if family == 9 && grade == 11 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Master_Perk_5) >= 1 { owned += 1; };
  };
  if family == 10 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Milestone_1) >= 1 { owned += 1; };
  };
  if family == 10 && grade == 2 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Milestone_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Perk_1_1) >= 1 { owned += 1; };
  };
  if family == 10 && grade == 3 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Milestone_2) >= 2 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Perk_1_2) >= 1 { owned += 1; };
  };
  if family == 10 && grade == 4 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Perk_2_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Perk_1_3) >= 1 { owned += 1; };
  };
  if family == 10 && grade == 5 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Milestone_3) >= 3 { owned += 1; };
  };
  if family == 10 && grade == 6 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Milestone_3) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Milestone_3) >= 2 { owned += 1; };
  };
  if family == 10 && grade == 7 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Perk_2_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Perk_2_3) >= 1 { owned += 1; };
  };
  if family == 10 && grade == 8 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Perk_2_4) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Inbetween_Left_3) >= 1 { owned += 1; };
  };
  if family == 10 && grade == 9 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Perk_3_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Perk_3_3) >= 1 { owned += 1; };
  };
  if family == 10 && grade == 10 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Central_Perk_3_2) >= 1 { owned += 1; };
  };
  if family == 10 && grade == 11 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Master_Perk_3) >= 1 { owned += 1; };
  };
  if family == 11 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Left_Milestone_2) >= 2 { owned += 1; };
  };
  if family == 11 && grade == 2 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Left_Milestone_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Left_Milestone_1) >= 1 { owned += 1; };
  };
  if family == 11 && grade == 3 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Left_Perk_2_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Left_Perk_2_4) >= 1 { owned += 1; };
  };
  if family == 11 && grade == 4 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Left_Perk_3_2) >= 1 { owned += 1; };
  };
  if family == 11 && grade == 5 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Left_Milestone_3) >= 3 { owned += 1; };
  };
  if family == 11 && grade == 6 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Left_Milestone_3) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Left_Milestone_3) >= 2 { owned += 1; };
  };
  if family == 11 && grade == 7 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Left_Perk_1_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Left_Perk_1_2) >= 1 { owned += 1; };
  };
  if family == 11 && grade == 8 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Left_Perk_2_3) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Left_Perk_2_1) >= 1 { owned += 1; };
  };
  if family == 11 && grade == 9 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Inbetween_Left_2) >= 1 { owned += 1; };
  };
  if family == 11 && grade == 10 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Left_Perk_3_4) >= 1 { owned += 1; };
  };
  if family == 11 && grade == 11 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Master_Perk_1) >= 1 { owned += 1; };
  };
  if family == 12 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Right_Milestone_2) >= 1 { owned += 1; };
  };
  if family == 12 && grade == 2 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Right_Milestone_2) >= 2 { owned += 1; };
  };
  if family == 12 && grade == 3 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Right_Perk_2_1) >= 1 { owned += 1; };
  };
  if family == 12 && grade == 4 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Right_Perk_2_2) >= 1 { owned += 1; };
  };
  if family == 12 && grade == 5 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Right_Milestone_3) >= 2 { owned += 1; };
  };
  if family == 12 && grade == 6 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Right_Milestone_3) >= 1 { owned += 1; };
  };
  if family == 12 && grade == 7 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Right_Milestone_3) >= 3 { owned += 1; };
  };
  if family == 12 && grade == 8 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Inbetween_Right_2) >= 1 { owned += 1; };
  };
  if family == 12 && grade == 9 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Right_Perk_3_2) >= 1 { owned += 1; };
  };
  if family == 12 && grade == 10 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Master_Perk_4) >= 1 { owned += 1; };
  };
  if family == 12 && grade == 11 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Right_Perk_3_1) >= 1 { owned += 1; };
  };
  if family == 13 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Central_Milestone_1) >= 1 { owned += 1; };
  };
  if family == 13 && grade == 2 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Central_Milestone_3) >= 1 { owned += 1; };
  };
  if family == 13 && grade == 3 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Central_Perk_1_1) >= 1 { owned += 1; };
  };
  if family == 13 && grade == 4 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Central_Milestone_3) >= 2 { owned += 1; };
  };
  if family == 13 && grade == 5 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Central_Milestone_3) >= 3 { owned += 1; };
  };
  if family == 13 && grade == 6 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Central_Perk_1_2) >= 1 { owned += 1; };
  };
  if family == 13 && grade == 7 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Central_Perk_1_4) >= 1 { owned += 1; };
  };
  if family == 13 && grade == 8 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Central_Perk_3_1) >= 1 { owned += 1; };
  };
  if family == 13 && grade == 9 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Central_Perk_3_4) >= 1 { owned += 1; };
  };
  if family == 13 && grade == 10 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Inbetween_Left_3) >= 1 { owned += 1; };
  };
  if family == 13 && grade == 11 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Central_Perk_3_2) >= 1 { owned += 1; };
  };
  if family == 14 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Right_Milestone_1) >= 1 { owned += 1; };
  };
  if family == 14 && grade == 2 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Right_Milestone_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Right_Perk_1_1) >= 1 { owned += 1; };
  };
  if family == 14 && grade == 3 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Right_Milestone_2) >= 2 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Right_Perk_2_1) >= 1 { owned += 1; };
  };
  if family == 14 && grade == 4 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Right_Perk_2_2) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Right_Perk_2_3) >= 1 { owned += 1; };
  };
  if family == 14 && grade == 5 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Right_Milestone_3) >= 3 { owned += 1; };
  };
  if family == 14 && grade == 6 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Right_Milestone_3) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Right_Milestone_3) >= 2 { owned += 1; };
  };
  if family == 14 && grade == 7 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Right_Perk_2_4) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Right_Perk_1_2) >= 1 { owned += 1; };
  };
  if family == 14 && grade == 8 {
    total = 2;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Right_Perk_3_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Right_Perk_3_4) >= 1 { owned += 1; };
  };
  if family == 14 && grade == 9 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Right_Perk_3_2) >= 1 { owned += 1; };
  };
  if family == 14 && grade == 10 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Inbetween_Right_3) >= 1 { owned += 1; };
  };
  if family == 14 && grade == 11 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Master_Perk_4) >= 1 { owned += 1; };
  };
  if family == 15 && grade == 1 {
    total = 5;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Body_Right_Milestone_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Cool_Left_Milestone_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Intelligence_Right_Milestone_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Reflexes_Left_Milestone_1) >= 1 { owned += 1; };
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Right_Milestone_1) >= 1 { owned += 1; };
  };
  if family == 22 && grade == 1 {
    total = 1;
    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.Tech_Central_Perk_3_2) >= 1 { owned += 1; };
  };
  if total == 0 { return 3; };
  if owned == total { return 2; };
  return owned > 0 ? 1 : 0;
}
