"""Generate ShardPerkSync.generated.reds: which vanilla perk ranks each shard
grade stands for, used to convert a save's bought perks into recorded grades."""

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = json.loads((ROOT / "design/other-shard-catalog.json").read_text(encoding="utf-8"))
LEDGER = list(csv.DictReader((ROOT / "design/perk-ledger.csv").open(encoding="utf-8")))

# Deadeye (family 0), from design/DEADEYE_ORDER.md.
DEADEYE = [
    [("Cool_Left_Milestone_2", 2)],
    [("Cool_Left_Milestone_2", 1), ("Cool_Left_Perk_2_2", 1)],
    [("Cool_Inbetween_Left_2", 1), ("Cool_Left_Perk_2_4", 1)],
    [("Cool_Left_Perk_2_1", 1), ("Cool_Left_Perk_2_3", 1)],
    [("Cool_Left_Milestone_3", 3)],
    [("Cool_Left_Milestone_3", 1), ("Cool_Left_Perk_3_3", 1)],
    [("Cool_Left_Perk_3_1", 1), ("Cool_Left_Perk_3_4", 1)],
    [("Cool_Left_Perk_3_2", 1)],
    [("Cool_Left_Milestone_3", 2)],
    [("Cool_Master_Perk_2", 1)],
    [("Cool_Master_Perk_1", 1)],
]


def grades():
    out = {0: DEADEYE}
    for family_id, family in enumerate(CATALOG, 1):
        out[family_id] = [[(e["perk"].split(".", 1)[1], int(e.get("rank", 1))) for e in g["effects"] if e.get("perk")]
                          for g in CATALOG[family]["grades"]]
    out[15] = [[(r["record_id"].split(".", 1)[1], 1) for r in LEDGER if r["family"] == "Vehicle"]]
    out[22] = [[("Tech_Central_Perk_3_2", 1)]]   # Hands Expansion = Ambidextrous
    return out


def main():
    lines = ["// Generated by tools/GeneratePerkSync.py. Do not edit manually.", "module SkillDrivenProgression", "",
             "// Status of a shard grade in the save's vanilla perk purchases:",
             "// 0 none bought, 1 partly bought, 2 fully bought, 3 grade has no vanilla perks.",
             "@addMethod(PlayerDevelopmentData)",
             "public final const func SDP_SyncGradeStatus(family: Int32, grade: Int32) -> Int32 {",
             "  let total: Int32 = 0;", "  let owned: Int32 = 0;"]
    for family, rows in grades().items():
        for grade, perks in enumerate(rows, 1):
            if not perks:
                continue
            lines.append(f"  if family == {family} && grade == {grade} {{")
            lines.append(f"    total = {len(perks)};")
            for perk, rank in perks:
                lines.append(f"    if this.SDP_VanillaPerkLevel(gamedataNewPerkType.{perk}) >= {rank} {{ owned += 1; }};")
            lines.append("  };")
    lines += ["  if total == 0 { return 3; };", "  if owned == total { return 2; };",
              "  return owned > 0 ? 1 : 0;", "}", ""]
    (ROOT / "r6/scripts/SkillDrivenProgression/ShardPerkSync.generated.reds").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
