"""Compile an isolated TestLab overlay and build a first-install Vortex ZIP.

This command never installs, enables, deploys, or writes to the game or Vortex.
The existing Deploy-Mods.py helper does not own this new package yet.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import zipfile

MODULE = Path(__file__).resolve().parents[1]
WORKSPACE = MODULE.parent
DEFAULT_GAME = Path('C:/Program Files (x86)/Steam/steamapps/common/Cyberpunk 2077')
RUNTIME_ROOTS = ('r6', 'bin', 'archive')
EXCLUDED_NAMES = ('db.sqlite3', 'settings.json', '__folder_managed_by_vortex')
COMPATIBILITY = {
    'EquipmentEx/EquipmentEx.reds': [
        ('this.m_filtersRadioGroup.SetData(this.m_filterManager.GetIntFiltersList());',
         'let sdpCompatFilterList = this.m_filterManager.GetIntFiltersList();\n        this.m_filtersRadioGroup.SetData(sdpCompatFilterList);')],
    'RedscriptConfigFramework/DVRCF_HubPopup.reds': [
        ('let spaces: Int32 = ArraySize(StrSplit(label, " ")) - 1;',
         'let sdpCompatLabelParts = StrSplit(label, " ");\n    let spaces: Int32 = ArraySize(sdpCompatLabelParts) - 1;'),
        ('let count: Int32 = ArraySize(RedLogger.LogFilesIn(lp.source, this.m_schema.tabs[0].sections[this.m_activeSection].name));',
         'let sdpCompatLogFiles = RedLogger.LogFilesIn(lp.source, this.m_schema.tabs[0].sections[this.m_activeSection].name);\n            let count: Int32 = ArraySize(sdpCompatLogFiles);')],
    'CombatArena/arena_spawner.reds': [
        (f'return GetPlayer(GetGameInstance()).GetWorldPosition().{axis};',
         f'let sdpCompatPlayerPosition = GetPlayer(GetGameInstance()).GetWorldPosition();\n    return sdpCompatPlayerPosition.{axis};')
        for axis in ('X', 'Y', 'Z')],
    'CombatArena/Terminal.reds': [
        ('if this.m_shopTab == 1 { rows = ArraySize(sys.GetPerks()); };',
         'if this.m_shopTab == 1 { let sdpCompatPerks = sys.GetPerks(); rows = ArraySize(sdpCompatPerks); };'),
        ('let total = this.m_shopTab == 0 ? ArraySize(sys.GetWeapons()) : ArraySize(sys.GetAllies());',
         'let sdpCompatWeapons = sys.GetWeapons();\n    let sdpCompatAllies = sys.GetAllies();\n    let total = this.m_shopTab == 0 ? ArraySize(sdpCompatWeapons) : ArraySize(sdpCompatAllies);', 2)],
}


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def collect_payload(module: Path) -> dict[str, Path]:
    files = {}
    for folder in RUNTIME_ROOTS:
        for path in sorted((module / folder).rglob('*')):
            if not path.is_file():
                continue
            if not path.resolve().is_relative_to(module.resolve()):
                raise ValueError(f'Runtime link escapes module: {path}')
            name = path.name.lower()
            if name in EXCLUDED_NAMES or name.endswith(('.log', '.vortex_backup', '.pyc')) or name.startswith('db.sqlite3'):
                continue
            # Reports are generated by the CET client, never shipped as fixtures.
            relative = path.relative_to(module)
            if any(part.lower() in ('reports', '__pycache__') for part in relative.parts):
                continue
            files[relative.as_posix()] = path
    if not files:
        raise ValueError(f'No runtime files under {module}')
    return files


def snapshot(files: dict[str, Path]) -> dict[str, str]:
    return {relative: digest(path) for relative, path in sorted(files.items())}


def write_json(path: Path, value) -> None:
    path.write_text(json.dumps(value, indent=2) + '\n', encoding='utf-8')


def compile_overlay(files: dict[str, Path], game: Path, compiler: Path, run: Path) -> dict:
    bundle = game / 'r6/cache/final.redscripts'
    if not bundle.is_file() or not compiler.is_file():
        raise FileNotFoundError('Game final.redscripts bundle or standalone compiler missing')
    shadow = run / 'compile/scripts'
    inputs = {}
    for source in (game / 'r6/scripts').rglob('*.reds'):
        relative = source.relative_to(game / 'r6/scripts')
        # TestLab owns its script directory: do not compile stale installed files.
        if relative.parts[0].lower() == 'sdptestlab':
            continue
        target = shadow / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
        inputs[source.as_posix()] = digest(source)
    for relative, source in files.items():
        if relative.startswith('r6/scripts/') and relative.endswith('.reds'):
            target = shadow / Path(relative).relative_to('r6/scripts')
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
    adapted = []
    for relative, replacements in COMPATIBILITY.items():
        target = shadow / relative
        if not target.exists():
            continue
        source = target.read_text(encoding='utf-8')
        for replacement in replacements:
            before, after = replacement[:2]
            expected_count = replacement[2] if len(replacement) > 2 else 1
            if before not in source:
                continue
            if source.count(before) != expected_count:
                raise ValueError(f'Ambiguous temporary compiler adaptation: {relative}')
            source = source.replace(before, after)
            adapted.append({'file': relative, 'expression': before, 'occurrences': expected_count})
        target.write_text(source, encoding='utf-8')
    plugin_files = list((game / 'red4ext/plugins').rglob('*.reds'))
    for source in [bundle, compiler, *plugin_files]:
        inputs[source.as_posix()] = digest(source)
    compatibility = {
        'excluded': [],
        'temporary_copy_only': adapted,
        'limitations': [
            'Standalone compiler validation is not an in-game compile or gameplay test.',
            'CombatArena and the installed mod scripts are included; plugin scripts are read from the installed game.',
            'Known temporary-value expressions are rewritten only in the validation copy; individual adaptations are recorded.',
        ],
    }
    write_json(run / 'compile-compatibility.json', compatibility)
    write_json(run / 'compile-inputs.json', inputs)
    output = run / 'compile/verified.redscripts'
    result = subprocess.run([
        str(compiler), 'compile', '-s', str(shadow),
        '-s', str(game / 'red4ext/plugins'), '-b', str(bundle), '-o', str(output),
    ], capture_output=True, text=True, encoding='utf-8', errors='replace')
    log = result.stdout + result.stderr
    (run / 'compile.log').write_text(log, encoding='utf-8')
    if result.returncode or not output.exists() or 'Output successfully saved' not in log:
        print(log[-12000:])
        raise RuntimeError(f'Compile failed; no ZIP built. See {run / "compile.log"}')
    for source, expected in inputs.items():
        if digest(Path(source)) != expected:
            raise RuntimeError(f'Compiler input changed during validation: {source}')
    return {'status': 'passed_with_documented_adaptations', 'log': str(run / 'compile.log'),
            'compatibility': compatibility, 'game_bundle_sha256': inputs[bundle.as_posix()]}


def make_zip(files: dict[str, Path], hashes: dict[str, str], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix='.testlab-package-', suffix='.zip', dir=output.parent)
    os.close(fd)
    try:
        with zipfile.ZipFile(temporary, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
            for relative, path in sorted(files.items()):
                data = path.read_bytes()
                if hashlib.sha256(data).hexdigest() != hashes[relative]:
                    raise RuntimeError(f'Source changed since validation; rebuild: {relative}')
                info = zipfile.ZipInfo(relative, date_time=(2026, 1, 1, 0, 0, 0))
                info.compress_type = zipfile.ZIP_DEFLATED
                info.external_attr = 0o100644 << 16
                archive.writestr(info, data)
        with zipfile.ZipFile(temporary) as archive:
            if archive.namelist() != sorted(files):
                raise RuntimeError('ZIP payload differs from planned files')
            for relative in archive.namelist():
                if hashlib.sha256(archive.read(relative)).hexdigest() != hashes[relative]:
                    raise RuntimeError(f'ZIP hash mismatch: {relative}')
        os.replace(temporary, output)
    finally:
        if Path(temporary).exists():
            Path(temporary).unlink()


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--game', type=Path, default=DEFAULT_GAME)
    parser.add_argument('--compiler', type=Path, default=WORKSPACE / 'redscript-cli.exe')
    parser.add_argument('--output', type=Path, default=MODULE / 'dist/SDP-TestLab-0.1.0.zip')
    parser.add_argument('--skip-compile', action='store_true', help='Package only; manifest explicitly records uncompiled status')
    args = parser.parse_args(argv)
    files = collect_payload(MODULE)
    hashes = snapshot(files)
    validation = MODULE / '.validation'
    validation.mkdir(exist_ok=True)
    run = Path(tempfile.mkdtemp(prefix=datetime.now().strftime('%Y%m%d-%H%M%S-'), dir=validation))
    write_json(run / 'payload-inputs.json', hashes)
    result = {'status': 'skipped', 'limitations': ['Standalone compilation was explicitly skipped.']}
    if not args.skip_compile:
        result = compile_overlay(files, args.game.resolve(), args.compiler.resolve(), run)
    if snapshot(files) != hashes:
        raise RuntimeError('Runtime source changed during validation; rebuild')
    output = args.output.resolve()
    make_zip(files, hashes, output)
    manifest = {
        'module': 'SDP-TestLab', 'version': '0.1.0',
        'built_at_utc': datetime.now(timezone.utc).isoformat(),
        'package': output.name, 'package_sha256': digest(output),
        'runtime_files': hashes, 'compile': result,
        'deployed': False, 'runtime_verified': False,
    }
    write_json(output.with_suffix('.manifest.json'), manifest)
    write_json(run / 'result.json', manifest)
    print(f'PASS: ZIP payload verified ({len(files)} runtime files): {output}')
    print(f'Compile: {result["status"]}; report: {run}')
    print('No game or Vortex files changed. Install/enable the ZIP in Vortex and deploy with the game closed.')


if __name__ == '__main__':
    main()
