"""Generate LooseFlats.reds: the loose flats each effector and prerequisite class reads.

Effector records such as PlayVFXEffector are the generic Effector record type,
and scripted prerequisites (IsPlayerPrereq, NPCRarityPrereq...) the generic
IPrereq type. Their data (vfxName, activationSFXName, attackPositionSlotName,
playerAsInstigator, invert, rarity...) are flats that the class's Initialize
reads by name, so reflection over the record class cannot list them. The
native dump (NativeDump.reds) prints them from this table.

Usage (decompiled scripts as in MakeScriptStubs.py):
    git clone --depth 1 https://codeberg.org/adamsmasher/cyberpunk.git
    python tools/MakeLooseFlats.py <cyberpunk-clone>
"""
import re
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "r6/scripts/SDPQuickhackCrafting/LooseFlats.reds"
CLASS = re.compile(r"class (\w+) extends (\w+) \{")
GET = re.compile(r'(?:TweakDBInterface|TDB)\.Get(\w+?)\(\s*(?:this\.)?\w*[Rr]ecord\w*\s*\+\s*t"\.(\w+)"')
# Getter -> type label the dump understands without Codeware.
TYPES = {"Bool": "Bool", "CName": "CName", "Float": "Float", "Int": "Int32", "String": "String",
         "ForeignKey": "TweakDBID", "ForeignKeyDefault": "TweakDBID", "StringArray": "array:String",
         "CNameArray": "array:CName", "FloatArray": "array:Float", "ForeignKeyArray": "array:TweakDBID",
         "Vector3": "Vector3"}
BASES = {"Effector", "ContinuousEffector", "IScriptablePrereq"}


def body_at(text, start):
    depth, i = 1, start
    while i < len(text) and depth:
        depth += {"{": 1, "}": -1}.get(text[i], 0)
        i += 1
    return text[start:i]


def main(clone):
    classes = {}
    for path in sorted(Path(clone).rglob("*.swift")):
        text = path.read_text(encoding="utf-8", errors="ignore")
        for match in CLASS.finditer(text):
            classes[match.group(1)] = (match.group(2), body_at(text, match.end()))

    def scripted(name):
        seen = set()
        while name in classes and name not in seen:
            seen.add(name)
            if classes[name][0] in BASES:
                return True
            name = classes[name][0]
        return False

    table = {}
    for name, (_, body) in sorted(classes.items()):
        if not scripted(name) or not re.search(r"func Initialize\((?:record|recordID): TweakDBID", body):
            continue
        flats = []
        for getter, flat in GET.findall(body):
            entry = f"{flat}:{TYPES.get(getter, getter)}"
            if entry not in flats:
                flats.append(entry)
        if flats:
            table[name] = flats

    lines = [
        "// Generated by tools/MakeEffectorFlats.py from the decompiled game scripts.",
        "// The loose flats each effector and scripted prerequisite class reads in",
        "// Initialize (\"name:type\"). Their records are the generic Effector and",
        "// IPrereq types, so reflection cannot list these flats. NativeDump.reds",
        "// prints them next to the record's own fields.",
        "module SkillDrivenProgression",
        "",
        "public func SDPQH_LooseFlats(className: CName) -> array<String> {",
        "  switch className {",
    ]
    for name, flats in table.items():
        lines.append(f"    case n\"{name}\": return [{', '.join(f'\"{f}\"' for f in flats)}];")
    lines += ["  };", "  let none: array<String>;", "  return none;", "}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {len(table)} effector and prerequisite classes to {OUT}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
