# Shard XP model for training v2 (design/SHARD_TRAINING_V2.md).
# Inputs: the game's own skill curves (design/native_curves.csv, dumped by the
# CET mod) and the logged fights. Writes design/SHARD_XP_MODEL.md.
# Principle: native skill progression is assumed balanced; shards reuse its
# formula and curve shape, scaled.
import csv
import itertools
from pathlib import Path

root = Path(__file__).resolve().parents[1]

# ---- Native data (from the game) --------------------------------------------
rows = list(csv.reader((root / "design/native_curves.csv").open(encoding="utf-8")))[1:]
LEVEL_XP = [int(float(r[1])) for r in rows]          # XP needed to reach level L from L-1
DAMAGE_CURVE = [float(r[6]) for r in rows]           # damage_to_skill_xp by enemy power level
LEVEL_MULT = [float(r[7]) for r in rows]             # player_level_to_xp_mult by player level
RARITY_NAMES = ["trash", "weak", "normal", "rare", "officer", "elite", "boss"]
RARITY = {n: float(rows[0][8 + i]) for i, n in enumerate(RARITY_NAMES)}  # power_level_to_dmg_xp_mult (flat)

# ---- Observed (logged fights, 2026-10-01; player level <= 15) ---------------
FIGHT_SECONDS = [64, 105, 28, 53, 184]
SOLO_XP = [282, 231, 343, 188, 419]     # tech shotgun: Solo at half rate (not a Power weapon)
DASHES = [12, 13]
QUEUED = [2, 2]

# ---- Assumptions --------------------------------------------------------------
END_PLAYER_LEVEL = 50        # player level reached by the end of main + sides + Phantom Liberty
SHARD_SHARE = 0.10           # shard channel XP = native skill XP formula x 0.10
MASTERY_FIGHTS = 200         # focused fights to master a shard started at the beginning of the game
SLOTS = 3                    # shards trained at once (processor slots)
SLOT_EFFICIENCY = 0.7        # secondary slots train slower than the main playstyle
MULT_GROWTH = 0.05           # channel multiplier gained per grade from perks (x1.0 -> x1.5)
GRADES = ["Tier 1", "Tier 1+", "Tier 2", "Tier 2+", "Tier 3", "Tier 3+",
          "Tier 4", "Tier 4+", "Tier 5", "Tier 5+", "Tier 5++"]
OLD = [150, 160, 170, 180, 190, 200, 220, 240, 260, 280, 300]

def mean(v):
    return sum(v) / len(v)

fight_s = mean(FIGHT_SECONDS)
# A focused fight at multiplier 1: Solo XP / level mult (0.48) / half-rate weapon (0.5) would
# double-count; use Solo as observed at 0.48 (a typical non-Power weapon fight).
base_fight = mean(SOLO_XP) / LEVEL_MULT[0]

def fight_xp(f, n):
    level = min(END_PLAYER_LEVEL, 1 + (END_PLAYER_LEVEL - 1) * f / n)
    i = int(level) - 1
    return base_fight * LEVEL_MULT[i] * DAMAGE_CURVE[i]

# Fights in a playthrough: the count at which a skill used all game reaches 60.
total_native = sum(LEVEL_XP)
fights = next(n for n in range(100, 2000, 10) if sum(fight_xp(f, n) for f in range(n)) >= total_native)
per_fight = [fight_xp(f, fights) * SHARD_SHARE for f in range(fights)]

# Grade bands follow the native curve: grade g ~ native levels 5g-4 .. 5g.
bands = [sum(LEVEL_XP[5 * g:5 * g + 5]) for g in range(11)]
cum = list(itertools.accumulate(per_fight))
scale = cum[MASTERY_FIGHTS - 1] / sum(bands)
thresholds = [int(round(scale * b * (1 + MULT_GROWTH * g) / 10.0)) * 10 for g, b in enumerate(bands)]

def fights_per_grade(start):
    out, f = [], start
    for g, t in enumerate(thresholds):
        need, s = t, f
        while need > 0 and f < fights:
            need -= per_fight[f] * (1 + MULT_GROWTH * g)
            f += 1
        out.append(f - s)
    return out

early, mid = fights_per_grade(0), fights_per_grade(fights // 2)
L = []
L += ["# Shard XP model (training v2)", "",
      "Generated by `tools/ShardXPModel.py` from the game's own curves (`design/native_curves.csv`)",
      "and the logged fights. Change an assumption there and re-run.", "",
      "These are planning estimates at 100% shard XP, not measured playthrough guarantees.",
      "The assumed player-level trajectory is not derived from this mod's five-skill average;",
      "specialist builds can remain at a lower XP multiplier for much longer. See",
      "[SPECIALIST_BALANCE.md](SPECIALIST_BALANCE.md) before using these fight counts as targets.", "",
      "## 1. Native skill progression (from the game files)", "",
      f"- XP per skill level: {LEVEL_XP[1]} (level 2) rising ~6-8% per level to {LEVEL_XP[-1]} (level 60); "
      f"**{total_native:,} XP** to reach 60. Level 50 is only half of that ({sum(LEVEL_XP[:50]):,}).",
      f"- Every skill XP award is multiplied by the **player-level multiplier**: x{LEVEL_MULT[0]:.2f} up to "
      f"level 15, x{LEVEL_MULT[39]:.2f} at 40, x{LEVEL_MULT[49]:.2f} from 50; and by the enemy-level damage "
      f"curve (x{DAMAGE_CURVE[0]:.2f} -> x{DAMAGE_CURVE[-1]:.2f}). A late fight is worth ~{fight_xp(fights-1, fights) / fight_xp(0, fights):.1f}x an early one.",
      "- Damage XP = damage curve x enemy rarity multiplier x % of the enemy's Health dealt x player-level",
      "  multiplier (x0.5 for non-Power guns).",
      "- Enemy rarity multipliers (same at every level): "
      + ", ".join(f"{n} x{RARITY[n]:g}" for n in RARITY_NAMES) + ".",
      f"  Full Health of a normal enemy = 100 native XP at x1; a boss = {100 * RARITY['boss']:.0f}.",
      f"- The logged Solo XP (half-rate shotgun) = {mean(SOLO_XP) / LEVEL_MULT[0] / 0.5:.0f} native XP at x1 full rate, i.e. about "
      f"**{mean(SOLO_XP) / LEVEL_MULT[0] / 0.5 / 100:.0f} normal-enemy Health bars** of damage per fight.", "",
      "## 2. Fights in a playthrough (derived, assuming native is balanced)", "",
      f"- Logged fights: {fight_s:.0f} s of combat; Solo (tech shotgun, half rate) **{mean(SOLO_XP):.0f} XP** "
      f"per fight at x{LEVEL_MULT[0]:.2f} = **{base_fight:.0f}** at x1.",
      f"- If a skill used all game is meant to hit 60 around player level {END_PLAYER_LEVEL} "
      f"(end of main + sides + Phantom Liberty: ~60 h + 20-30 h), a playthrough has **~{fights} fights**",
      f"  (~{fights / 85:.0f} per hour over ~85 h).", "",
      "## 3. Shard budget", "",
      f"- Shard channel XP = **native formula x {SHARD_SHARE}** (same multipliers), so a focused fight gives "
      f"~{per_fight[0]:.0f} shard XP early, ~{per_fight[fights // 2]:.0f} mid-game, ~{per_fight[-1]:.0f} late.",
      f"- {SLOTS} shards train at once: {fights} fights x {SLOTS} slots x {SLOT_EFFICIENCY:.0%} efficiency = "
      f"~{fights * SLOTS * SLOT_EFFICIENCY:.0f} focused shard-fights.",
      f"- Mastering a shard from the start of the game takes **{sum(early)} focused fights**, from mid-game "
      f"**{sum(mid)}**; a playthrough masters **~{fights * SLOTS * SLOT_EFFICIENCY / ((sum(early) + sum(mid)) / 2):.0f} of 16 shards**",
      "  under these assumptions. Different builds, settings and farming change that estimate.", "",
      "## 4. XP per grade", "",
      "Grade g uses the native XP of skill levels 5g-4..5g (same curve shape), scaled so mastery takes "
      f"{MASTERY_FIGHTS} fights from game start, times the perk multiplier growth (1 + {MULT_GROWTH} x (g-1)).", "",
      "| Grade | Native levels | XP to record | Cumulative | Fights (from start) | Fights (from mid-game) | Old v1 |",
      "|---|---|---:|---:|---:|---:|---:|"]
c = 0
for g, (name, t) in enumerate(zip(GRADES, thresholds)):
    c += t
    L.append(f"| {name} | {5 * g + 1}-{5 * g + 5} | **{t}** | {c} | {early[g]} | {mid[g]} | {OLD[g]} |")
dash, queued = mean(DASHES), mean(QUEUED)
unit = base_fight * SHARD_SHARE           # shard XP of a focused fight at multiplier 1
rate_s = unit / fight_s
L += ["", "## 5. Channel rates (at multiplier 1; all are then x player-level multiplier)", "",
      f"A focused fight is worth **{unit:.0f} shard XP at x1** ({fight_s:.0f} s), so:", "",
      "| Channel type | Rate | Why |", "|---|---|---|",
      f"| Damage share (weapons, hacks, explosions) | native damage XP x {SHARD_SHARE * 0.5:g}: {50 * SHARD_SHARE:g} per enemy Health bar x rarity (trash {50 * SHARD_SHARE * RARITY['trash']:g} ... boss {50 * SHARD_SHARE * RARITY['boss']:g}) | the x{SHARD_SHARE} share applied to the typical half-rate gun the fight value was measured with; one rate for every weapon |",
      f"| Time in a state (wounded, crouched near enemies, Overdrive) | {rate_s:.2f} XP/s | {unit:.0f} XP over a {fight_s:.0f} s fight |",
      f"| Dash / dodge / slide / vault in combat | {unit / dash:.1f} XP each | you made {dash:.1f} per fight |",
      f"| Queued quickhack | {unit / (queued * 8):.1f} XP per RAM | {queued:.0f} queued per fight, ~8 RAM each |",
      f"| Health lost and survived | {unit * 0.5 / 1.5:.0f} XP per max-Health bar | ~1.5 bars per fight = half a fight's value |",
      f"| Events (Obliterate, finisher, item use, kill in Adrenaline Rush) | {unit / 5:.0f} XP each | 1-3 per fight |",
      "", "## 6. Limiters", "",
      f"- Time and event channels: at most {unit * 4 * 10 / fight_s:.0f} XP (x multipliers) per 10 s window, 4x the average pace.",
      "  Damage channels have no window cap; the per-target cap below bounds them.",
      "- Per target/family: damage XP stops at 100% health share while its entry remains in the",
      "  bounded session cache (160 entries; reset on reload). This limits repeated damage but",
      "  is not a persistent anti-farming guarantee. A boss pays up to "
      f"{50 * SHARD_SHARE * RARITY['boss']:.0f} shard XP at x1",
      f"  (x{RARITY['boss']:g}, about {50 * SHARD_SHARE * RARITY['boss'] / unit:.1f} focused fights), an elite {50 * SHARD_SHARE * RARITY['elite']:.0f}, trash {50 * SHARD_SHARE * RARITY['trash']:g}.",
      "- Time channels require combat except Ninjutsu Shadow, which requires nearby watchers",
      "  before combat and stops paying after 5 seconds at one spot (move over 3 m to reset).",
      "- The per-family 0-500% setting multiplies XP after the base limiter; fractional XP",
      "  carries across actions and saves. At 0%, the carry and window budget are unchanged.", ""]
(root / "design/SHARD_XP_MODEL.md").write_text("\n".join(L), encoding="utf-8", newline="\n")
print("\n".join(L))
