// Generated from design/shard-training.json. Edit that file to retune awards.
module SkillDrivenProgression

public func SDP_TrainingThreshold(grade: Int32) -> Int32 {
  if grade == 1 { return 150; };
  if grade == 2 { return 160; };
  if grade == 3 { return 170; };
  if grade == 4 { return 180; };
  if grade == 5 { return 190; };
  if grade == 6 { return 200; };
  if grade == 7 { return 220; };
  if grade == 8 { return 240; };
  if grade == 9 { return 260; };
  if grade == 10 { return 280; };
  if grade == 11 { return 300; };
  return 0;
}

public func SDP_TrainingFamilyThreshold(family: Int32, grade: Int32) -> Int32 {
  if family < 1 || family > 15 { return 0; };
  if family == 15 && grade != 1 { return 0; };
  if family == 1 && grade == 2 { return 80; };
  if family == 1 && grade == 4 { return 90; };
  if family == 1 && grade == 6 { return 100; };
  if family == 1 && grade == 8 { return 120; };
  if family == 1 && grade == 10 { return 140; };
  if family == 2 && grade == 3 { return 85; };
  if family == 2 && grade == 4 { return 90; };
  if family == 2 && grade == 6 { return 100; };
  if family == 2 && grade == 8 { return 120; };
  if family == 2 && grade == 10 { return 140; };
  if family == 3 && grade == 3 { return 85; };
  if family == 3 && grade == 4 { return 90; };
  if family == 3 && grade == 6 { return 100; };
  if family == 3 && grade == 8 { return 120; };
  if family == 3 && grade == 10 { return 140; };
  if family == 4 && grade == 3 { return 85; };
  if family == 4 && grade == 4 { return 90; };
  if family == 4 && grade == 6 { return 100; };
  if family == 4 && grade == 8 { return 120; };
  if family == 4 && grade == 10 { return 140; };
  if family == 5 && grade == 3 { return 85; };
  if family == 5 && grade == 4 { return 90; };
  if family == 5 && grade == 6 { return 100; };
  if family == 5 && grade == 8 { return 120; };
  if family == 5 && grade == 10 { return 140; };
  if family == 6 && grade == 3 { return 85; };
  if family == 6 && grade == 4 { return 90; };
  if family == 6 && grade == 6 { return 100; };
  if family == 6 && grade == 8 { return 120; };
  if family == 6 && grade == 10 { return 140; };
  if family == 7 && grade == 2 { return 80; };
  if family == 7 && grade == 4 { return 90; };
  if family == 7 && grade == 6 { return 100; };
  if family == 7 && grade == 8 { return 120; };
  if family == 7 && grade == 10 { return 140; };
  if family == 8 && grade == 2 { return 80; };
  if family == 8 && grade == 4 { return 90; };
  if family == 8 && grade == 6 { return 100; };
  if family == 8 && grade == 8 { return 120; };
  if family == 8 && grade == 10 { return 140; };
  if family == 9 && grade == 2 { return 80; };
  if family == 9 && grade == 4 { return 90; };
  if family == 9 && grade == 6 { return 100; };
  if family == 9 && grade == 8 { return 120; };
  if family == 9 && grade == 10 { return 140; };
  if family == 10 && grade == 2 { return 80; };
  if family == 10 && grade == 4 { return 90; };
  if family == 10 && grade == 6 { return 100; };
  if family == 10 && grade == 8 { return 120; };
  if family == 10 && grade == 10 { return 140; };
  if family == 11 && grade == 2 { return 80; };
  if family == 11 && grade == 4 { return 90; };
  if family == 11 && grade == 6 { return 100; };
  if family == 11 && grade == 8 { return 120; };
  if family == 11 && grade == 10 { return 140; };
  if family == 12 && grade == 3 { return 85; };
  if family == 12 && grade == 4 { return 90; };
  if family == 12 && grade == 6 { return 100; };
  if family == 12 && grade == 8 { return 120; };
  if family == 12 && grade == 10 { return 140; };
  if family == 13 && grade == 2 { return 80; };
  if family == 13 && grade == 4 { return 90; };
  if family == 13 && grade == 6 { return 100; };
  if family == 13 && grade == 8 { return 120; };
  if family == 13 && grade == 10 { return 140; };
  if family == 14 && grade == 3 { return 85; };
  if family == 14 && grade == 4 { return 90; };
  if family == 14 && grade == 6 { return 100; };
  if family == 14 && grade == 8 { return 120; };
  if family == 14 && grade == 10 { return 140; };
  return SDP_TrainingThreshold(grade);
}

public func SDP_TrainingDeadeyeSourceGrade(source: Int32) -> Int32 {
  if source == 1 { return 1; };
  if source == 2 { return 2; };
  if source == 3 { return 2; };
  if source == 4 { return 2; };
  if source == 5 { return 3; };
  if source == 6 { return 4; };
  if source == 7 { return 4; };
  if source == 8 { return 5; };
  if source == 9 { return 6; };
  if source == 10 { return 7; };
  if source == 11 { return 7; };
  if source == 12 { return 8; };
  if source == 13 { return 9; };
  if source == 14 { return 10; };
  if source == 15 { return 11; };
  return 0;
}

public func SDP_TrainingDeadeyeAward(source: Int32, grade: Int32) -> Int32 {
  if source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  if source == 2 && grade >= 2 { return grade == 2 ? 2 : 1; };
  if source == 3 && grade >= 2 { return grade == 2 ? 2 : 1; };
  if source == 4 && grade >= 2 { return grade == 2 ? 2 : 1; };
  if source == 5 && grade >= 3 { return grade == 3 ? 2 : 1; };
  if source == 6 && grade >= 4 { return grade == 4 ? 2 : 1; };
  if source == 7 && grade >= 4 { return grade == 4 ? 2 : 1; };
  if source == 8 && grade >= 5 { return grade == 5 ? 2 : 1; };
  if source == 9 && grade >= 6 { return grade == 6 ? 2 : 1; };
  if source == 10 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if source == 11 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if source == 12 && grade >= 8 { return grade == 8 ? 2 : 1; };
  if source == 13 && grade >= 9 { return grade == 9 ? 2 : 1; };
  if source == 14 && grade >= 10 { return grade == 10 ? 2 : 1; };
  if source == 15 && grade >= 11 { return grade == 11 ? 2 : 1; };
  return 0;
}

public func SDP_TrainingFamilyAward(family: Int32, source: Int32, grade: Int32) -> Int32 {
  if family == 1 && source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  if family == 1 && source == 2 && grade >= 3 { return grade == 3 ? 2 : 1; };
  if family == 1 && source == 3 && grade >= 5 { return grade == 5 ? 2 : 1; };
  if family == 1 && source == 4 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if family == 1 && source == 5 && grade >= 9 { return grade == 9 ? 2 : 1; };
  if family == 1 && source == 6 && grade >= 11 { return grade == 11 ? 2 : 1; };
  if family == 2 && source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  if family == 2 && source == 2 && grade >= 5 { return grade == 5 ? 2 : 1; };
  if family == 2 && source == 3 && grade >= 2 { return grade == 2 ? 2 : 1; };
  if family == 2 && source == 4 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if family == 2 && source == 5 && grade >= 9 { return grade == 9 ? 2 : 1; };
  if family == 2 && source == 6 && grade >= 11 { return grade == 11 ? 2 : 1; };
  if family == 3 && source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  if family == 3 && source == 2 && grade >= 2 { return grade == 2 ? 2 : 1; };
  if family == 3 && source == 3 && grade >= 5 { return grade == 5 ? 2 : 1; };
  if family == 3 && source == 4 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if family == 3 && source == 5 && grade >= 9 { return grade == 9 ? 2 : 1; };
  if family == 3 && source == 6 && grade >= 11 { return grade == 11 ? 2 : 1; };
  if family == 4 && source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  if family == 4 && source == 2 && grade >= 5 { return grade == 5 ? 2 : 1; };
  if family == 4 && source == 3 && grade >= 2 { return grade == 2 ? 2 : 1; };
  if family == 4 && source == 4 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if family == 4 && source == 5 && grade >= 9 { return grade == 9 ? 2 : 1; };
  if family == 4 && source == 6 && grade >= 11 { return grade == 11 ? 2 : 1; };
  if family == 5 && source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  if family == 5 && source == 2 && grade >= 2 { return grade == 2 ? 2 : 1; };
  if family == 5 && source == 3 && grade >= 5 { return grade == 5 ? 2 : 1; };
  if family == 5 && source == 4 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if family == 5 && source == 5 && grade >= 9 { return grade == 9 ? 2 : 1; };
  if family == 5 && source == 6 && grade >= 11 { return grade == 11 ? 2 : 1; };
  if family == 6 && source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  if family == 6 && source == 2 && grade >= 5 { return grade == 5 ? 2 : 1; };
  if family == 6 && source == 3 && grade >= 2 { return grade == 2 ? 2 : 1; };
  if family == 6 && source == 4 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if family == 6 && source == 5 && grade >= 9 { return grade == 9 ? 2 : 1; };
  if family == 6 && source == 6 && grade >= 11 { return grade == 11 ? 2 : 1; };
  if family == 7 && source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  if family == 7 && source == 2 && grade >= 3 { return grade == 3 ? 2 : 1; };
  if family == 7 && source == 3 && grade >= 5 { return grade == 5 ? 2 : 1; };
  if family == 7 && source == 4 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if family == 7 && source == 5 && grade >= 9 { return grade == 9 ? 2 : 1; };
  if family == 7 && source == 6 && grade >= 11 { return grade == 11 ? 2 : 1; };
  if family == 8 && source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  if family == 8 && source == 2 && grade >= 3 { return grade == 3 ? 2 : 1; };
  if family == 8 && source == 3 && grade >= 5 { return grade == 5 ? 2 : 1; };
  if family == 8 && source == 4 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if family == 8 && source == 5 && grade >= 9 { return grade == 9 ? 2 : 1; };
  if family == 8 && source == 6 && grade >= 11 { return grade == 11 ? 2 : 1; };
  if family == 9 && source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  if family == 9 && source == 2 && grade >= 9 { return grade == 9 ? 2 : 1; };
  if family == 9 && source == 3 && grade >= 3 { return grade == 3 ? 2 : 1; };
  if family == 9 && source == 4 && grade >= 5 { return grade == 5 ? 2 : 1; };
  if family == 9 && source == 5 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if family == 9 && source == 6 && grade >= 11 { return grade == 11 ? 2 : 1; };
  if family == 10 && source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  if family == 10 && source == 2 && grade >= 3 { return grade == 3 ? 2 : 1; };
  if family == 10 && source == 3 && grade >= 5 { return grade == 5 ? 2 : 1; };
  if family == 10 && source == 4 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if family == 10 && source == 5 && grade >= 9 { return grade == 9 ? 2 : 1; };
  if family == 10 && source == 6 && grade >= 11 { return grade == 11 ? 2 : 1; };
  if family == 11 && source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  if family == 11 && source == 2 && grade >= 3 { return grade == 3 ? 2 : 1; };
  if family == 11 && source == 3 && grade >= 5 { return grade == 5 ? 2 : 1; };
  if family == 11 && source == 4 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if family == 11 && source == 5 && grade >= 9 { return grade == 9 ? 2 : 1; };
  if family == 11 && source == 6 && grade >= 11 { return grade == 11 ? 2 : 1; };
  if family == 12 && source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  if family == 12 && source == 2 && grade >= 2 { return grade == 2 ? 2 : 1; };
  if family == 12 && source == 3 && grade >= 5 { return grade == 5 ? 2 : 1; };
  if family == 12 && source == 4 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if family == 12 && source == 5 && grade >= 9 { return grade == 9 ? 2 : 1; };
  if family == 12 && source == 6 && grade >= 11 { return grade == 11 ? 2 : 1; };
  if family == 13 && source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  if family == 13 && source == 2 && grade >= 3 { return grade == 3 ? 2 : 1; };
  if family == 13 && source == 3 && grade >= 5 { return grade == 5 ? 2 : 1; };
  if family == 13 && source == 4 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if family == 13 && source == 5 && grade >= 9 { return grade == 9 ? 2 : 1; };
  if family == 13 && source == 6 && grade >= 11 { return grade == 11 ? 2 : 1; };
  if family == 14 && source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  if family == 14 && source == 2 && grade >= 5 { return grade == 5 ? 2 : 1; };
  if family == 14 && source == 3 && grade >= 2 { return grade == 2 ? 2 : 1; };
  if family == 14 && source == 4 && grade >= 7 { return grade == 7 ? 2 : 1; };
  if family == 14 && source == 5 && grade >= 9 { return grade == 9 ? 2 : 1; };
  if family == 14 && source == 6 && grade >= 11 { return grade == 11 ? 2 : 1; };
  if family == 15 && source == 1 && grade >= 1 { return grade == 1 ? 2 : 1; };
  return 0;
}

public func SDP_TrainingFamilySourceGrade(family: Int32, source: Int32) -> Int32 {
  if family == 1 && source == 1 { return 1; };
  if family == 1 && source == 2 { return 3; };
  if family == 1 && source == 3 { return 5; };
  if family == 1 && source == 4 { return 7; };
  if family == 1 && source == 5 { return 9; };
  if family == 1 && source == 6 { return 11; };
  if family == 2 && source == 1 { return 1; };
  if family == 2 && source == 2 { return 5; };
  if family == 2 && source == 3 { return 2; };
  if family == 2 && source == 4 { return 7; };
  if family == 2 && source == 5 { return 9; };
  if family == 2 && source == 6 { return 11; };
  if family == 3 && source == 1 { return 1; };
  if family == 3 && source == 2 { return 2; };
  if family == 3 && source == 3 { return 5; };
  if family == 3 && source == 4 { return 7; };
  if family == 3 && source == 5 { return 9; };
  if family == 3 && source == 6 { return 11; };
  if family == 4 && source == 1 { return 1; };
  if family == 4 && source == 2 { return 5; };
  if family == 4 && source == 3 { return 2; };
  if family == 4 && source == 4 { return 7; };
  if family == 4 && source == 5 { return 9; };
  if family == 4 && source == 6 { return 11; };
  if family == 5 && source == 1 { return 1; };
  if family == 5 && source == 2 { return 2; };
  if family == 5 && source == 3 { return 5; };
  if family == 5 && source == 4 { return 7; };
  if family == 5 && source == 5 { return 9; };
  if family == 5 && source == 6 { return 11; };
  if family == 6 && source == 1 { return 1; };
  if family == 6 && source == 2 { return 5; };
  if family == 6 && source == 3 { return 2; };
  if family == 6 && source == 4 { return 7; };
  if family == 6 && source == 5 { return 9; };
  if family == 6 && source == 6 { return 11; };
  if family == 7 && source == 1 { return 1; };
  if family == 7 && source == 2 { return 3; };
  if family == 7 && source == 3 { return 5; };
  if family == 7 && source == 4 { return 7; };
  if family == 7 && source == 5 { return 9; };
  if family == 7 && source == 6 { return 11; };
  if family == 8 && source == 1 { return 1; };
  if family == 8 && source == 2 { return 3; };
  if family == 8 && source == 3 { return 5; };
  if family == 8 && source == 4 { return 7; };
  if family == 8 && source == 5 { return 9; };
  if family == 8 && source == 6 { return 11; };
  if family == 9 && source == 1 { return 1; };
  if family == 9 && source == 2 { return 9; };
  if family == 9 && source == 3 { return 3; };
  if family == 9 && source == 4 { return 5; };
  if family == 9 && source == 5 { return 7; };
  if family == 9 && source == 6 { return 11; };
  if family == 10 && source == 1 { return 1; };
  if family == 10 && source == 2 { return 3; };
  if family == 10 && source == 3 { return 5; };
  if family == 10 && source == 4 { return 7; };
  if family == 10 && source == 5 { return 9; };
  if family == 10 && source == 6 { return 11; };
  if family == 11 && source == 1 { return 1; };
  if family == 11 && source == 2 { return 3; };
  if family == 11 && source == 3 { return 5; };
  if family == 11 && source == 4 { return 7; };
  if family == 11 && source == 5 { return 9; };
  if family == 11 && source == 6 { return 11; };
  if family == 12 && source == 1 { return 1; };
  if family == 12 && source == 2 { return 2; };
  if family == 12 && source == 3 { return 5; };
  if family == 12 && source == 4 { return 7; };
  if family == 12 && source == 5 { return 9; };
  if family == 12 && source == 6 { return 11; };
  if family == 13 && source == 1 { return 1; };
  if family == 13 && source == 2 { return 3; };
  if family == 13 && source == 3 { return 5; };
  if family == 13 && source == 4 { return 7; };
  if family == 13 && source == 5 { return 9; };
  if family == 13 && source == 6 { return 11; };
  if family == 14 && source == 1 { return 1; };
  if family == 14 && source == 2 { return 5; };
  if family == 14 && source == 3 { return 2; };
  if family == 14 && source == 4 { return 7; };
  if family == 14 && source == 5 { return 9; };
  if family == 14 && source == 6 { return 11; };
  if family == 15 && source == 1 { return 1; };
  return 0;
}
