// Generated from design/shard-training.json. Run tools/GenerateShardTrainingLabels.py after editing it.
module SkillDrivenProgression

public func SDP_TrainingFamilySourceName(family: Int32, source: Int32) -> String {
  if family == 1 && source == 1 { return "Survive a hit of at least 20 damage in combat"; };
  if family == 1 && source == 2 { return "Survive a combat hit with under half Health remaining"; };
  if family == 1 && source == 3 { return "Survive a combat hit of at least 40 damage"; };
  if family == 1 && source == 4 { return "Survive at least 40 damage with under half Health remaining"; };
  if family == 1 && source == 5 { return "Survive a combat hit of at least 60 damage"; };
  if family == 1 && source == 6 { return "Survive a combat hit with under 30% Health remaining"; };
  if family == 2 && source == 1 { return "Damage a hostile with a shotgun or LMG"; };
  if family == 2 && source == 2 { return "Neutralize one within 8 m with a shotgun or LMG"; };
  if family == 2 && source == 3 { return "Land a shotgun or LMG headshot or weakspot hit"; };
  if family == 2 && source == 4 { return "Land a shotgun or LMG critical hit"; };
  if family == 2 && source == 5 { return "Damage a hostile within 5 m with a shotgun or LMG"; };
  if family == 2 && source == 6 { return "Neutralize a hostile within 5 m with a shotgun or LMG"; };
  if family == 3 && source == 1 { return "Damage a hostile with a blunt weapon"; };
  if family == 3 && source == 2 { return "Force a knockdown with a blunt hit"; };
  if family == 3 && source == 3 { return "Neutralize a hostile with a blunt weapon"; };
  if family == 3 && source == 4 { return "Land a critical blunt hit"; };
  if family == 3 && source == 5 { return "Land a critical blunt neutralization"; };
  if family == 3 && source == 6 { return "Neutralize a hostile with a blunt hit within 5 m"; };
  if family == 4 && source == 1 { return "Dash during combat"; };
  if family == 4 && source == 2 { return "Air dash during combat"; };
  if family == 4 && source == 3 { return "Land a precision hit shortly after a ground dash"; };
  if family == 4 && source == 4 { return "Land a precision hit shortly after an air dash"; };
  if family == 4 && source == 5 { return "Neutralize a hostile shortly after an air dash"; };
  if family == 4 && source == 6 { return "Land a critical hit shortly after an air dash"; };
  if family == 5 && source == 1 { return "Damage a hostile with an assault rifle or SMG"; };
  if family == 5 && source == 2 { return "Add a headshot or weakspot hit with that weapon"; };
  if family == 5 && source == 3 { return "Land a critical assault rifle or SMG hit"; };
  if family == 5 && source == 4 { return "Damage a hostile from at least 25 m with an assault rifle or SMG"; };
  if family == 5 && source == 5 { return "Neutralize with an assault rifle or SMG headshot or weakspot hit"; };
  if family == 5 && source == 6 { return "Land a critical precision assault rifle or SMG hit"; };
  if family == 6 && source == 1 { return "Damage a hostile with a blade"; };
  if family == 6 && source == 2 { return "Neutralize a hostile with a blade"; };
  if family == 6 && source == 3 { return "Land a critical blade hit"; };
  if family == 6 && source == 4 { return "Damage a hostile with a stealth blade hit"; };
  if family == 6 && source == 5 { return "Neutralize a hostile with a critical blade hit"; };
  if family == 6 && source == 6 { return "Neutralize a hostile with a blade within 5 m"; };
  if family == 7 && source == 1 { return "Damage a hostile with a cyberarm"; };
  if family == 7 && source == 2 { return "Neutralize a hostile with a cyberarm"; };
  if family == 7 && source == 3 { return "Land a critical cyberarm hit"; };
  if family == 7 && source == 4 { return "Damage a hostile with the Projectile Launch System"; };
  if family == 7 && source == 5 { return "Deal at least 100 damage to a hostile with a cyberarm"; };
  if family == 7 && source == 6 { return "Neutralize a hostile with a critical cyberarm hit"; };
  if family == 8 && source == 1 { return "Damage a hostile with an explosion"; };
  if family == 8 && source == 2 { return "Neutralize a hostile with an explosion"; };
  if family == 8 && source == 3 { return "Deal at least 100 explosion damage to a hostile"; };
  if family == 8 && source == 4 { return "Damage a hostile with an explosion from at least 15 m away"; };
  if family == 8 && source == 5 { return "Deal at least 200 explosion damage to a hostile"; };
  if family == 8 && source == 6 { return "Neutralize a hostile with an explosion dealing at least 100 damage"; };
  if family == 9 && source == 1 { return "Damage a hostile with a fully charged Tech shot"; };
  if family == 9 && source == 2 { return "Add a headshot or weakspot hit with that shot"; };
  if family == 9 && source == 3 { return "Land a critical fully charged Tech shot"; };
  if family == 9 && source == 4 { return "Neutralize a hostile with a fully charged Tech shot"; };
  if family == 9 && source == 5 { return "Damage a hostile from at least 25 m with a fully charged Tech shot"; };
  if family == 9 && source == 6 { return "Land a critical precision fully charged Tech shot"; };
  if family == 10 && source == 1 { return "Damage a hostile with a quickhack"; };
  if family == 10 && source == 2 { return "Deal at least 50 damage to a hostile with a quickhack"; };
  if family == 10 && source == 3 { return "Neutralize a hostile with a quickhack"; };
  if family == 10 && source == 4 { return "Deal at least 100 damage to a hostile with a quickhack"; };
  if family == 10 && source == 5 { return "Deal at least 150 damage to a hostile with a quickhack"; };
  if family == 10 && source == 6 { return "Neutralize a hostile with a quickhack dealing at least 100 damage"; };
  if family == 11 && source == 1 { return "Queue a second quickhack on a hostile"; };
  if family == 11 && source == 2 { return "Queue a third quickhack on a hostile"; };
  if family == 11 && source == 3 { return "Neutralize a hostile with a queued quickhack"; };
  if family == 11 && source == 4 { return "Queue a fourth quickhack on a hostile"; };
  if family == 11 && source == 5 { return "Deal at least 100 damage with a queued quickhack"; };
  if family == 11 && source == 6 { return "Neutralize a hostile with a quickhack while at least three hacks are queued"; };
  if family == 12 && source == 1 { return "Damage a hostile with a Smart weapon"; };
  if family == 12 && source == 2 { return "Add a headshot or weakspot hit with that weapon"; };
  if family == 12 && source == 3 { return "Land a critical Smart-weapon hit"; };
  if family == 12 && source == 4 { return "Damage a hostile from at least 25 m with a Smart weapon"; };
  if family == 12 && source == 5 { return "Neutralize a hostile with a Smart weapon"; };
  if family == 12 && source == 6 { return "Neutralize a hostile with a Smart-weapon headshot or weakspot hit"; };
  if family == 13 && source == 1 { return "Neutralize a hostile with a stealth hit"; };
  if family == 13 && source == 2 { return "Damage a hostile with a stealth hit"; };
  if family == 13 && source == 3 { return "Land a stealth headshot or weakspot hit"; };
  if family == 13 && source == 4 { return "Neutralize a hostile with a ranged stealth hit"; };
  if family == 13 && source == 5 { return "Neutralize a hostile with a stealth hit from at least 25 m"; };
  if family == 13 && source == 6 { return "Neutralize a hostile with a critical stealth hit"; };
  if family == 14 && source == 1 { return "Damage a hostile with a thrown knife or axe"; };
  if family == 14 && source == 2 { return "Neutralize a hostile with that throw"; };
  if family == 14 && source == 3 { return "Land a thrown knife or axe headshot or weakspot hit"; };
  if family == 14 && source == 4 { return "Damage a hostile with a stealth knife or axe throw"; };
  if family == 14 && source == 5 { return "Land a critical knife or axe throw"; };
  if family == 14 && source == 6 { return "Neutralize a hostile with a precision knife or axe throw"; };
  if family == 15 && source == 1 { return "Damage a hostile with a vehicle weapon"; };
  return "unknown action";
}
