// Generated from design/other-shard-catalog.json and design/shard-training.json.
module SkillDrivenProgression

public func SDP_RecordedEffectTitle(family: Int32, grade: Int32) -> String {
  if family == 0 && grade == 1 { return "Focus"; };
  if family == 0 && grade == 2 { return "Focus precision + Rinse and Reload"; };
  if family == 0 && grade == 3 { return "Deep Breath + No Sweat"; };
  if family == 0 && grade == 4 { return "Head to Head + Pull!"; };
  if family == 0 && grade == 5 { return "Deadeye"; };
  if family == 0 && grade == 6 { return "Deadeye precision + Long Shot"; };
  if family == 0 && grade == 7 { return "Quick Draw + California Reaper"; };
  if family == 0 && grade == 8 { return "High Noon"; };
  if family == 0 && grade == 9 { return "Deadeye efficiency"; };
  if family == 0 && grade == 10 { return "Run 'N' Gun"; };
  if family == 0 && grade == 11 { return "Nerves of Tungsten-Steel"; };
  if family == 1 && grade == 1 { return "Painkiller"; };
  if family == 1 && grade == 2 { return "Adrenaline Rush 1"; };
  if family == 1 && grade == 3 { return "Speed Junkie + Comeback Kid"; };
  if family == 1 && grade == 4 { return "Adrenaline Rush 2"; };
  if family == 1 && grade == 5 { return "Adrenaline Rush 3"; };
  if family == 1 && grade == 6 { return "Dorph-head"; };
  if family == 1 && grade == 7 { return "Army of One"; };
  if family == 1 && grade == 8 { return "Calm Mind + Bloodlust"; };
  if family == 1 && grade == 9 { return "Juggernaut"; };
  if family == 1 && grade == 10 { return "Unstoppable Force"; };
  if family == 1 && grade == 11 { return "Pain to Gain"; };
  if family == 2 && grade == 1 { return "Die! Die! Die! 1"; };
  if family == 2 && grade == 2 { return "Die! Die! Die! 2"; };
  if family == 2 && grade == 3 { return "Bullet Ballet + Like a Feather"; };
  if family == 2 && grade == 4 { return "Spontaneous Obliteration 1"; };
  if family == 2 && grade == 5 { return "Spontaneous Obliteration 3"; };
  if family == 2 && grade == 6 { return "Spontaneous Obliteration 2 + Don't Stop Me Now"; };
  if family == 2 && grade == 7 { return "Rush of Blood"; };
  if family == 2 && grade == 8 { return "Skullcracker"; };
  if family == 2 && grade == 9 { return "Dread"; };
  if family == 2 && grade == 10 { return "Close-quarters Carnage"; };
  if family == 2 && grade == 11 { return "Rip and Tear + Onslaught"; };
  if family == 3 && grade == 1 { return "Wrecking Ball 1"; };
  if family == 3 && grade == 2 { return "Wrecking Ball 2"; };
  if family == 3 && grade == 3 { return "Fly Swatter + Kinetic Absorption"; };
  if family == 3 && grade == 4 { return "Clapback"; };
  if family == 3 && grade == 5 { return "Quake 3"; };
  if family == 3 && grade == 6 { return "Quake 1 + Quake 2"; };
  if family == 3 && grade == 7 { return "Breakthrough"; };
  if family == 3 && grade == 8 { return "Aftershock"; };
  if family == 3 && grade == 9 { return "Epicenter"; };
  if family == 3 && grade == 10 { return "Ripple Effect"; };
  if family == 3 && grade == 11 { return "Finisher"; };
  if family == 4 && grade == 1 { return "Slippery"; };
  if family == 4 && grade == 2 { return "Dash 2"; };
  if family == 4 && grade == 3 { return "Dash 1 + Power Slide"; };
  if family == 4 && grade == 4 { return "Muscle Memory + Parkour!"; };
  if family == 4 && grade == 5 { return "Air Dash 3"; };
  if family == 4 && grade == 6 { return "Air Dash 1 + Air Dash 2"; };
  if family == 4 && grade == 7 { return "Can't Touch This + Mean Streak"; };
  if family == 4 && grade == 8 { return "Steady Grip + Multitasker"; };
  if family == 4 && grade == 9 { return "Aerial Acrobat + Aerodynamic"; };
  if family == 4 && grade == 10 { return "Mad Dash"; };
  if family == 4 && grade == 11 { return "Tailwind"; };
  if family == 5 && grade == 1 { return "Ready, Rested, Reloaded 1"; };
  if family == 5 && grade == 2 { return "Ready, Rested, Reloaded 2"; };
  if family == 5 && grade == 3 { return "Spice of Life + Mind Over Matter"; };
  if family == 5 && grade == 4 { return "Sharpshooter 1"; };
  if family == 5 && grade == 5 { return "Sharpshooter 3"; };
  if family == 5 && grade == 6 { return "Sharpshooter 2 + Practice Makes Perfect"; };
  if family == 5 && grade == 7 { return "Tunnel Vision + Gundancer"; };
  if family == 5 && grade == 8 { return "Spray and Pray + Air Kerenzikov"; };
  if family == 5 && grade == 9 { return "Shoot to Chill"; };
  if family == 5 && grade == 10 { return "Submachine Fun"; };
  if family == 5 && grade == 11 { return "Salt in the Wound"; };
  if family == 6 && grade == 1 { return "Lead and Steel 1"; };
  if family == 6 && grade == 2 { return "Lead and Steel 2"; };
  if family == 6 && grade == 3 { return "Bullet Deflect + Seeing Double"; };
  if family == 6 && grade == 4 { return "Bullet Time"; };
  if family == 6 && grade == 5 { return "Finisher"; };
  if family == 6 && grade == 6 { return "Finisher"; };
  if family == 6 && grade == 7 { return "Flash and Thunderclap"; };
  if family == 6 && grade == 8 { return "Opportunist"; };
  if family == 6 && grade == 9 { return "Going the Distance"; };
  if family == 6 && grade == 10 { return "Flash of Steel"; };
  if family == 6 && grade == 11 { return "Slaughterhouse"; };
  if family == 7 && grade == 1 { return "All Things Cyber 1"; };
  if family == 7 && grade == 2 { return "All Things Cyber 2"; };
  if family == 7 && grade == 3 { return "Driver Update + Lucky Day"; };
  if family == 7 && grade == 4 { return "License to Chrome 1"; };
  if family == 7 && grade == 5 { return "License to Chrome 3"; };
  if family == 7 && grade == 6 { return "License to Chrome 2 + Extended Warranty"; };
  if family == 7 && grade == 7 { return "Custom"; };
  if family == 7 && grade == 8 { return "Built Different"; };
  if family == 7 && grade == 9 { return "Renaissance Punk + Chipware Connoisseur"; };
  if family == 7 && grade == 10 { return "Chrome Constitution + Cyborg"; };
  if family == 7 && grade == 11 { return "Edgerunner"; };
  if family == 8 && grade == 1 { return "Glutton for War"; };
  if family == 8 && grade == 2 { return "Health Freak 1 + First Aid"; };
  if family == 8 && grade == 3 { return "Health Freak 2 + Transfusion"; };
  if family == 8 && grade == 4 { return "Demolitions Surplus + Coming in Hot"; };
  if family == 8 && grade == 5 { return "Pyromania 3"; };
  if family == 8 && grade == 6 { return "Pyromania 1 + 2"; };
  if family == 8 && grade == 7 { return "Friendlier Fire + Doomlauncher"; };
  if family == 8 && grade == 8 { return "Borrowed Time + Field Medic"; };
  if family == 8 && grade == 9 { return "Heat Shield + Burn This City"; };
  if family == 8 && grade == 10 { return "Flash Sale"; };
  if family == 8 && grade == 11 { return "Ticking Time Bomb"; };
  if family == 9 && grade == 1 { return "Bolt 1"; };
  if family == 9 && grade == 2 { return "Bolt 2"; };
  if family == 9 && grade == 3 { return "In Charge"; };
  if family == 9 && grade == 4 { return "Custom"; };
  if family == 9 && grade == 5 { return "Bolt 3"; };
  if family == 9 && grade == 6 { return "Internal Clock"; };
  if family == 9 && grade == 7 { return "Shock Value"; };
  if family == 9 && grade == 8 { return "Lightning Storm"; };
  if family == 9 && grade == 9 { return "Custom"; };
  if family == 9 && grade == 10 { return "Custom"; };
  if family == 9 && grade == 11 { return "Chain Lightning"; };
  if family == 10 && grade == 1 { return "Optimization"; };
  if family == 10 && grade == 2 { return "Embedded Exploit 1 + Encryption"; };
  if family == 10 && grade == 3 { return "Embedded Exploit 2 + Proximate Propagation"; };
  if family == 10 && grade == 4 { return "ICEpick + Subordination"; };
  if family == 10 && grade == 5 { return "Overclock 3"; };
  if family == 10 && grade == 6 { return "Overclock 1 + 2"; };
  if family == 10 && grade == 7 { return "Speculation + System Overwhelm"; };
  if family == 10 && grade == 8 { return "Shadowrunner + Blood Daemon"; };
  if family == 10 && grade == 9 { return "Race Against Mind + Power Surge"; };
  if family == 10 && grade == 10 { return "Sublimation"; };
  if family == 10 && grade == 11 { return "Spillover"; };
  if family == 11 && grade == 1 { return "Hack Queue 2"; };
  if family == 11 && grade == 2 { return "Hack Queue 1 + Eye in the Sky"; };
  if family == 11 && grade == 3 { return "Data Recycler + Feedback Loop"; };
  if family == 11 && grade == 4 { return "Queue Prioritization"; };
  if family == 11 && grade == 5 { return "Queue Acceleration 3"; };
  if family == 11 && grade == 6 { return "Queue Acceleration 1 + 2"; };
  if family == 11 && grade == 7 { return "Warning"; };
  if family == 11 && grade == 8 { return "Copy-Paste + Counter-a-hack"; };
  if family == 11 && grade == 9 { return "Siphon"; };
  if family == 11 && grade == 10 { return "Finisher"; };
  if family == 11 && grade == 11 { return "Queue Mastery"; };
  if family == 12 && grade == 1 { return "Acquisition Specialist 1"; };
  if family == 12 && grade == 2 { return "Acquisition Specialist 2"; };
  if family == 12 && grade == 3 { return "No Escape"; };
  if family == 12 && grade == 4 { return "Precision Subroutines"; };
  if family == 12 && grade == 5 { return "Target Lock Transfer 2"; };
  if family == 12 && grade == 6 { return "Target Lock Transfer 1"; };
  if family == 12 && grade == 7 { return "Target Lock Transfer 3"; };
  if family == 12 && grade == 8 { return "Recirculation"; };
  if family == 12 && grade == 9 { return "Terminal Velocity"; };
  if family == 12 && grade == 10 { return "Smart Synergy"; };
  if family == 12 && grade == 11 { return "Targeting Prism"; };
  if family == 13 && grade == 1 { return "Feline Footwork"; };
  if family == 13 && grade == 2 { return "Ninjutsu 1"; };
  if family == 13 && grade == 3 { return "Unexposed"; };
  if family == 13 && grade == 4 { return "Ninjutsu 2"; };
  if family == 13 && grade == 5 { return "Ninjutsu 3"; };
  if family == 13 && grade == 6 { return "Small Target"; };
  if family == 13 && grade == 7 { return "Blind Spot"; };
  if family == 13 && grade == 8 { return "Serpentine"; };
  if family == 13 && grade == 9 { return "Shinobi Sprint"; };
  if family == 13 && grade == 10 { return "Vanishing Act"; };
  if family == 13 && grade == 11 { return "Creeping Death"; };
  if family == 14 && grade == 1 { return "Killer Instinct"; };
  if family == 14 && grade == 2 { return "Scorpion Sting 1 + Gag Order"; };
  if family == 14 && grade == 3 { return "Scorpion Sting 2 + Corrosion"; };
  if family == 14 && grade == 4 { return "Neurotoxin + Accelerated Toxin Absorption"; };
  if family == 14 && grade == 5 { return "Juggler 3"; };
  if family == 14 && grade == 6 { return "Juggler 1 + 2"; };
  if family == 14 && grade == 7 { return "Parasite + Quick Getaway"; };
  if family == 14 && grade == 8 { return "Pay It Forward + Sleight of Hand"; };
  if family == 14 && grade == 9 { return "Finisher"; };
  if family == 14 && grade == 10 { return "Pounce"; };
  if family == 14 && grade == 11 { return "Style Over Substance"; };
  if family == 15 && grade == 1 { return "Road Warrior + Fury Road + Stuntjock + Carhacker + Gearhead"; };
  if family == 16 && grade == 1 { return "OS Expansion slots"; };
  if family == 17 && grade == 1 { return "Frontal Cortex Expansion slots"; };
  if family == 18 && grade == 1 { return "Cardiovascular Expansion slots"; };
  if family == 19 && grade == 1 { return "Nervous System Expansion slots"; };
  if family == 20 && grade == 1 { return "Integumentary Expansion slots"; };
  if family == 21 && grade == 1 { return "Arms Expansion slots"; };
  if family == 22 && grade == 1 { return "Hands Expansion slots"; };
  if family == 23 && grade == 1 { return "Legs Expansion slots"; };
  return "Unknown effect";
}

public func SDP_RecordedEffectDescription(family: Int32, grade: Int32) -> String {
  if family == 0 && grade == 1 { return "Focus: aim at full Stamina to enter Focus; shooting then costs no Stamina"; };
  if family == 0 && grade == 2 { return "Focus precision: more headshot and weakspot damage; Rinse and Reload: faster reload after aimed neutralization"; };
  if family == 0 && grade == 3 { return "Deep Breath: time slows during Focus; No Sweat: neutralizations reduce its ending Stamina cost"; };
  if family == 0 && grade == 4 { return "Head to Head: Focus refreshes after neutralization; Pull!: stronger airborne grenade shots"; };
  if family == 0 && grade == 5 { return "Deadeye: high Stamina improves precision damage and removes bullet spread"; };
  if family == 0 && grade == 6 { return "Deadeye precision: more headshot and weakspot damage; Long Shot: no damage falloff during Deadeye"; };
  if family == 0 && grade == 7 { return "Quick Draw: swaps restore Stamina; California Reaper: precision neutralizations restore Stamina"; };
  if family == 0 && grade == 8 { return "High Noon: precision neutralizations prime a faster slowed-time reload"; };
  if family == 0 && grade == 9 { return "Deadeye efficiency: shooting costs less Stamina"; };
  if family == 0 && grade == 10 { return "Run 'N' Gun: hip-fire costs no Stamina and Focus permits faster movement"; };
  if family == 0 && grade == 11 { return "Nerves of Tungsten-Steel: precision hits during Deadeye always crit and gain damage at range"; };
  if family == 1 && grade == 1 { return "Painkiller: slow Health regeneration in combat."; };
  if family == 1 && grade == 2 { return "Adrenaline Rush 1: more maximum Health."; };
  if family == 1 && grade == 3 { return "Speed Junkie + Comeback Kid: stronger regeneration while moving or wounded."; };
  if family == 1 && grade == 4 { return "Adrenaline Rush 2: boost all Health regeneration sources."; };
  if family == 1 && grade == 5 { return "Adrenaline Rush 3: Blood Pump and Health Items can grant Adrenaline."; };
  if family == 1 && grade == 6 { return "Dorph-head: mitigation after Blood Pump or a Health Item."; };
  if family == 1 && grade == 7 { return "Army of One: regeneration improves near enemies."; };
  if family == 1 && grade == 8 { return "Calm Mind + Bloodlust: delay Adrenaline decay and gain Adrenaline from nearby dismemberments."; };
  if family == 1 && grade == 9 { return "Juggernaut: move faster and deal more damage during Adrenaline Rush."; };
  if family == 1 && grade == 10 { return "Unstoppable Force: ignore movement penalties and non-damaging status effects during Adrenaline Rush."; };
  if family == 1 && grade == 11 { return "Pain to Gain: neutralizations during Adrenaline Rush recharge Health Items."; };
  if family == 2 && grade == 1 { return "Die! Die! Die! 1: Stamina regeneration."; };
  if family == 2 && grade == 2 { return "Die! Die! Die! 2: handling improves as Stamina falls."; };
  if family == 2 && grade == 3 { return "Bullet Ballet + Like a Feather: mobile firing and weapon movement."; };
  if family == 2 && grade == 4 { return "Spontaneous Obliteration 1: Crit Chance rises as Stamina falls."; };
  if family == 2 && grade == 5 { return "Spontaneous Obliteration 3: unlock Obliterate on weakened enemies."; };
  if family == 2 && grade == 6 { return "Spontaneous Obliteration 2 + Don't Stop Me Now: close-range damage and defense at low Stamina."; };
  if family == 2 && grade == 7 { return "Rush of Blood: faster reload after dismemberment."; };
  if family == 2 && grade == 8 { return "Skullcracker: stronger Quick Melee at low Stamina."; };
  if family == 2 && grade == 9 { return "Dread: ranged attacks reduce enemy Armor; dismemberment spreads it."; };
  if family == 2 && grade == 10 { return "Close-quarters Carnage: more ranged Obliterate chance up close."; };
  if family == 2 && grade == 11 { return "Rip and Tear + Onslaught: shotgun/Quick Melee damage loop or LMG ammo refill on neutralization."; };
  if family == 3 && grade == 1 { return "Wrecking Ball 1: lower blunt-attack Stamina cost."; };
  if family == 3 && grade == 2 { return "Wrecking Ball 2: sprint-block charge that can knock enemies down."; };
  if family == 3 && grade == 3 { return "Fly Swatter + Kinetic Absorption: ranged blocking defense and Stamina/damage from blocks."; };
  if family == 3 && grade == 4 { return "Clapback: stronger knockdown and stun counterattacks."; };
  if family == 3 && grade == 5 { return "Quake 3: ground or midair slam."; };
  if family == 3 && grade == 6 { return "Quake 1 + Quake 2: lower blunt Stamina cost and faster blunt attacks."; };
  if family == 3 && grade == 7 { return "Breakthrough: strong attacks lower enemy Armor."; };
  if family == 3 && grade == 8 { return "Aftershock: regain Stamina per enemy hit by Quake."; };
  if family == 3 && grade == 9 { return "Epicenter: midair Quake scales with fall speed and distance."; };
  if family == 3 && grade == 10 { return "Ripple Effect: gain Health per enemy hit by Quake."; };
  if family == 3 && grade == 11 { return "Finisher: Savage Sling: finish or throw a weakened enemy."; };
  if family == 4 && grade == 1 { return "Slippery: faster movement makes you harder to hit."; };
  if family == 4 && grade == 2 { return "Dash 2: unlock Dash."; };
  if family == 4 && grade == 3 { return "Dash 1 + Power Slide: cheaper Dash/dodge and longer slides."; };
  if family == 4 && grade == 4 { return "Muscle Memory + Parkour!: reload while moving and vault or climb faster."; };
  if family == 4 && grade == 5 { return "Air Dash 3: unlock midair Dash."; };
  if family == 4 && grade == 6 { return "Air Dash 1 + Air Dash 2: cheaper and faster Dashes."; };
  if family == 4 && grade == 7 { return "Can't Touch This + Mean Streak: mitigation during Dash and longer Dashes toward enemies."; };
  if family == 4 && grade == 8 { return "Steady Grip + Multitasker: fire during Dash and other movement actions."; };
  if family == 4 && grade == 9 { return "Aerial Acrobat + Aerodynamic: midair control and mitigation."; };
  if family == 4 && grade == 10 { return "Mad Dash: Stamina after a neutralization while Dashing."; };
  if family == 4 && grade == 11 { return "Tailwind: Air Dashes cost no Stamina and restore it."; };
  if family == 5 && grade == 1 { return "Ready, Rested, Reloaded 1: cheaper AR/SMG shooting."; };
  if family == 5 && grade == 2 { return "Ready, Rested, Reloaded 2: faster reload at high Stamina."; };
  if family == 5 && grade == 3 { return "Spice of Life + Mind Over Matter: faster swaps, less spread, less aimed recoil."; };
  if family == 5 && grade == 4 { return "Sharpshooter 1: faster aim."; };
  if family == 5 && grade == 5 { return "Sharpshooter 3: successful shots build Sharpshooter stacks."; };
  if family == 5 && grade == 6 { return "Sharpshooter 2 + Practice Makes Perfect: handling and Crit bonuses as stacks build."; };
  if family == 5 && grade == 7 { return "Tunnel Vision + Gundancer: effective range, mobile aiming, and vault shooting."; };
  if family == 5 && grade == 8 { return "Spray and Pray + Air Kerenzikov: cheaper hip-fire and a midair Kerenzikov option."; };
  if family == 5 && grade == 9 { return "Shoot to Chill: Armor penetration per Sharpshooter stack."; };
  if family == 5 && grade == 10 { return "Submachine Fun: SMG swaps auto-reload and briefly improve fire rate."; };
  if family == 5 && grade == 11 { return "Salt in the Wound: consecutive shots on the same target trigger bonus damage."; };
  if family == 6 && grade == 1 { return "Lead and Steel 1: cheaper blade attacks."; };
  if family == 6 && grade == 2 { return "Lead and Steel 2: block projectiles with a Blade."; };
  if family == 6 && grade == 3 { return "Bullet Deflect + Seeing Double: aimed deflections and stronger counterattacks."; };
  if family == 6 && grade == 4 { return "Bullet Time: enhanced deflections while time is slowed."; };
  if family == 6 && grade == 5 { return "Finisher: Bladerunner 3: unlock Blade Finisher."; };
  if family == 6 && grade == 6 { return "Finisher: Bladerunner 1 + 2: cheaper and faster Blade attacks."; };
  if family == 6 && grade == 7 { return "Flash and Thunderclap: leap toward enemies on Strong Attacks."; };
  if family == 6 && grade == 8 { return "Opportunist: more enemies become susceptible to Finishers."; };
  if family == 6 && grade == 9 { return "Going the Distance: longer Finisher reach."; };
  if family == 6 && grade == 10 { return "Flash of Steel: speed after a Finisher."; };
  if family == 6 && grade == 11 { return "Slaughterhouse: attacks and deflections apply Bleeding to set up Finishers."; };
  if family == 7 && grade == 1 { return "All Things Cyber 1: stronger cyberware stat modifiers."; };
  if family == 7 && grade == 2 { return "All Things Cyber 2: lower Capacity cost for Integumentary and Skeleton cyberware."; };
  if family == 7 && grade == 3 { return "Driver Update + Lucky Day: extra cyberware modifier and more looted components."; };
  if family == 7 && grade == 4 { return "License to Chrome 1: further cyberware stat modifiers."; };
  if family == 7 && grade == 5 { return "License to Chrome 3: additional Skeleton slot and Skeleton stat boost."; };
  if family == 7 && grade == 6 { return "License to Chrome 2 + Extended Warranty: Armor and longer cyberware effects."; };
  if family == 7 && grade == 7 { return "Custom: Chrome Calibration: +4 Cyberware Capacity. (Ambidextrous, the extra Hands slot, moved to the Hands Expansion shard.)"; };
  if family == 7 && grade == 8 { return "Built Different: unlock and support Cellular Adapter."; };
  if family == 7 && grade == 9 { return "Renaissance Punk + Chipware Connoisseur: skill-derived Capacity and cyberware upgrade choices."; };
  if family == 7 && grade == 10 { return "Chrome Constitution + Cyborg: rewards for filled cyberware slots."; };
  if family == 7 && grade == 11 { return "Edgerunner: exceed Capacity at a Health cost."; };
  if family == 8 && grade == 1 { return "Glutton for War: extra Health Item charge and recharge."; };
  if family == 8 && grade == 2 { return "Health Freak 1 + First Aid: faster item and grenade recharge."; };
  if family == 8 && grade == 3 { return "Health Freak 2 + Transfusion: recharge on neutralization and stronger final Health Item charge."; };
  if family == 8 && grade == 4 { return "Demolitions Surplus + Coming in Hot: more grenade supply and recharge."; };
  if family == 8 && grade == 5 { return "Pyromania 3: explosion hits build Pyromania movement/damage stacks."; };
  if family == 8 && grade == 6 { return "Pyromania 1 + 2: recharge and explosion-radius bonuses."; };
  if family == 8 && grade == 7 { return "Friendlier Fire + Doomlauncher: resist your own explosions; grenade perks also help Projectile Launch System."; };
  if family == 8 && grade == 8 { return "Borrowed Time + Field Medic: emergency item recovery and faster combat use."; };
  if family == 8 && grade == 9 { return "Heat Shield + Burn This City: stack-based mitigation and grenade replenishment."; };
  if family == 8 && grade == 10 { return "Flash Sale: greater Flash, Smoke, and Recon grenade supply."; };
  if family == 8 && grade == 11 { return "Ticking Time Bomb: delayed EMP on Operating System or Overclock activation."; };
  if family == 9 && grade == 1 { return "Bolt 1: faster Tech-weapon charging."; };
  if family == 9 && grade == 2 { return "Bolt 2: more charged-shot damage."; };
  if family == 9 && grade == 3 { return "In Charge: holding full charge no longer auto-fires."; };
  if family == 9 && grade == 4 { return "Custom: damaging fully charged Tech shots restore 2 Stamina."; };
  if family == 9 && grade == 5 { return "Bolt 3: unlock timed Bolt shots."; };
  if family == 9 && grade == 6 { return "Internal Clock: wider timing window for a Bolt."; };
  if family == 9 && grade == 7 { return "Shock Value: Bolt shots ignore Armor."; };
  if family == 9 && grade == 8 { return "Lightning Storm: repeated Bolts accelerate charging."; };
  if family == 9 && grade == 9 { return "Custom: Tech weapons gain 5% headshot damage while this grade is active."; };
  if family == 9 && grade == 10 { return "Custom: a fully charged Tech-shot neutralization restores 5 Stamina."; };
  if family == 9 && grade == 11 { return "Chain Lightning: Bolt deals Electrical damage and arcs to nearby enemies."; };
  if family == 10 && grade == 1 { return "Optimization: RAM recovery."; };
  if family == 10 && grade == 2 { return "Embedded Exploit 1 + Encryption: RAM recovery and lower traceability."; };
  if family == 10 && grade == 3 { return "Embedded Exploit 2 + Proximate Propagation: damage on prepared targets and cheaper close-range hacks."; };
  if family == 10 && grade == 4 { return "ICEpick + Subordination: prepared Combat hacks cost less; Control hacks last longer."; };
  if family == 10 && grade == 5 { return "Overclock 3: spend Health to quickhack without enough RAM."; };
  if family == 10 && grade == 6 { return "Overclock 1 + 2: RAM recovery and quickhack damage."; };
  if family == 10 && grade == 7 { return "Speculation + System Overwhelm: RAM refund on Combat-hack neutralizations and damage from layered effects."; };
  if family == 10 && grade == 8 { return "Shadowrunner + Blood Daemon: Takedowns reduce trace; queued hacks on an Overclock victim restore Health."; };
  if family == 10 && grade == 9 { return "Race Against Mind + Power Surge: low-Health damage and Health on Overclock activation."; };
  if family == 10 && grade == 10 { return "Sublimation: RAM recovery also regenerates Health during Overclock."; };
  if family == 10 && grade == 11 { return "Spillover: hacks can spread during Overclock."; };
  if family == 11 && grade == 1 { return "Hack Queue 2: unlock ordered quickhack queues."; };
  if family == 11 && grade == 2 { return "Hack Queue 1 + Eye in the Sky: Max RAM and camera/Access Point utility."; };
  if family == 11 && grade == 3 { return "Data Recycler + Feedback Loop: refund unused queued hacks and recover RAM while queuing."; };
  if family == 11 && grade == 4 { return "Queue Prioritization: faster upload at the start of a populated queue."; };
  if family == 11 && grade == 5 { return "Queue Acceleration 3: larger, faster late queue."; };
  if family == 11 && grade == 6 { return "Queue Acceleration 1 + 2: Max RAM and cheaper device/vehicle hacks."; };
  if family == 11 && grade == 7 { return "Warning: Explosion Hazard + ForceKill Cypher: device explosion and Access Point bonuses."; };
  if family == 11 && grade == 8 { return "Copy-Paste + Counter-a-hack: counter hostile netrunners and spread a counterhack."; };
  if family == 11 && grade == 9 { return "Siphon: Monowire attacks restore RAM."; };
  if family == 11 && grade == 10 { return "Finisher: Live Wire: Monowire Finisher improves with queued hacks."; };
  if family == 11 && grade == 11 { return "Queue Mastery: larger queue and a powerful final-slot reward."; };
  if family == 12 && grade == 1 { return "Acquisition Specialist 1: larger Smart-weapon targeting area."; };
  if family == 12 && grade == 2 { return "Acquisition Specialist 2: keep locks on reload and lock faster."; };
  if family == 12 && grade == 3 { return "No Escape: shooting a target can renew a fading lock."; };
  if family == 12 && grade == 4 { return "Precision Subroutines: accuracy scales with Max RAM; custom fallback: small flat accuracy bonus without a cyberdeck."; };
  if family == 12 && grade == 5 { return "Target Lock Transfer 2: keep head/weakspot lock between aiming and hip-fire."; };
  if family == 12 && grade == 6 { return "Target Lock Transfer 1: further enlarge the target area."; };
  if family == 12 && grade == 7 { return "Target Lock Transfer 3: keep locks when swapping Smart weapons."; };
  if family == 12 && grade == 8 { return "Recirculation: RAM after Smart-weapon neutralization; custom: Smart-weapon neutralizations also restore 5 Stamina."; };
  if family == 12 && grade == 9 { return "Terminal Velocity: Smart-weapon neutralizations improve projectile speed and range."; };
  if family == 12 && grade == 10 { return "Smart Synergy: instant lock and bonus damage during Overclock; custom: a small passive lock-speed bonus."; };
  if family == 12 && grade == 11 { return "Targeting Prism: lock multiple targets while aiming."; };
  if family == 13 && grade == 1 { return "Feline Footwork: faster, safer crouched movement."; };
  if family == 13 && grade == 2 { return "Ninjutsu 1: crouch movement speed."; };
  if family == 13 && grade == 3 { return "Unexposed: mitigation while aiming from cover."; };
  if family == 13 && grade == 4 { return "Ninjutsu 2: mitigation while crouched."; };
  if family == 13 && grade == 5 { return "Ninjutsu 3: unlock crouch-sprinting."; };
  if family == 13 && grade == 6 { return "Small Target: mitigation while crouched and still."; };
  if family == 13 && grade == 7 { return "Blind Spot: crouched mitigation delays detection."; };
  if family == 13 && grade == 8 { return "Serpentine: mitigation while crouch-sprinting."; };
  if family == 13 && grade == 9 { return "Shinobi Sprint: cheaper crouch-sprinting in combat."; };
  if family == 13 && grade == 10 { return "Vanishing Act: Optical Camo activates while crouch-sprinting or sliding."; };
  if family == 13 && grade == 11 { return "Creeping Death: stealth neutralizations restore Health/Stamina and grant speed."; };
  if family == 14 && grade == 1 { return "Killer Instinct: stronger knives, axes, and silenced guns outside combat."; };
  if family == 14 && grade == 2 { return "Scorpion Sting 1 + Gag Order: faster throwable recovery and delayed group detection."; };
  if family == 14 && grade == 3 { return "Scorpion Sting 2 + Corrosion: precision throws apply Poison, including to machines."; };
  if family == 14 && grade == 4 { return "Neurotoxin + Accelerated Toxin Absorption: control Poisoned enemies and cash out Poison with a hit."; };
  if family == 14 && grade == 5 { return "Juggler 3: qualifying thrown neutralizations reset throwable cooldowns."; };
  if family == 14 && grade == 6 { return "Juggler 1 + 2: faster recovery and more precision damage."; };
  if family == 14 && grade == 7 { return "Parasite + Quick Getaway: thrown precision hits heal; stealth neutralizations grant speed."; };
  if family == 14 && grade == 8 { return "Pay It Forward + Sleight of Hand: reward retrieved throws and Juggler activation."; };
  if family == 14 && grade == 9 { return "Finisher: Act of Mercy: Throwable Weapon Finisher."; };
  if family == 14 && grade == 10 { return "Pounce: longer Finisher reach after a thrown hit."; };
  if family == 14 && grade == 11 { return "Style Over Substance: guaranteed thrown Crits during skilled movement."; };
  if family == 15 && grade == 1 { return "Road Warrior, Fury Road, Stuntjock, Carhacker, and Gearhead vehicle perks."; };
  if family == 16 && grade == 1 { return "2 extra OS cyberware slot(s) (Cyberware-EX)"; };
  if family == 17 && grade == 1 { return "2 extra Frontal Cortex cyberware slot(s) (Cyberware-EX)"; };
  if family == 18 && grade == 1 { return "1 extra Cardiovascular cyberware slot(s) (Cyberware-EX)"; };
  if family == 19 && grade == 1 { return "1 extra Nervous System cyberware slot(s) (Cyberware-EX)"; };
  if family == 20 && grade == 1 { return "2 extra Integumentary cyberware slot(s) (Cyberware-EX)"; };
  if family == 21 && grade == 1 { return "1 extra Arms cyberware slot(s) (Cyberware-EX)"; };
  if family == 22 && grade == 1 { return "1 extra Hands cyberware slot(s) (Cyberware-EX)"; };
  if family == 23 && grade == 1 { return "1 extra Legs cyberware slot(s) (Cyberware-EX)"; };
  return "Unknown effect";
}
